// GRE Vocabulary Data
// Source: TestCrackers GRE Word List

const VOCAB_DATA = [
  { word: "Abate", definition: "Reduce, diminish, become less in amount or intensity", mnemonics: ["Abe ate all the food...now it's all gone", "Mosquito abatement - city sprays to kill mosquitos"] },
  { word: "Abdicate", definition: "Formally give up the throne or other power or responsibility", mnemonics: ["A dictate is a command; abdicate is to give up the power to dictate", "Queen Elizabeth's uncle in The Crown"] },
  { word: "Aberrant", definition: "Markedly different from an accepted norm", mnemonics: ["ab + errare = away + to stray from the normal"] },
  { word: "Abhor", definition: "Detest, regard with disgust", mnemonics: ["If it is ABsolutely HORrible, it should be abhorred"] },
  { word: "Abjure", definition: "Give up, renounce; repudiate, recant, or shun", mnemonics: ["ab + jurare = away from swearing", "A jury renounces media influence"] },
  { word: "Abrasive", definition: "Rough, suitable for grinding or polishing; causing irritation or annoyance", mnemonics: ["A bra can be aBRAsive"] },
  { word: "Abridge", definition: "Reduce or lessen; shorten by omitting parts while retaining main idea", mnemonics: ["A bridge allows you to omit certain parts of the trip", "Use the bridge for a shortcut"] },
  { word: "Abstain", definition: "Hold back, refrain especially from something bad or unhealthy", mnemonics: ["If you don't want to strain your abs, abstain from sit-ups"] },
  { word: "Acme", definition: "Summit, peak, highest point", mnemonics: ["Wile E. Coyote and Road Runner on a mountain top with ACME dynamite"] },
  { word: "Activism", definition: "Practice of pursuing political or other goals through vigorous action", mnemonics: ["Be ACTIVE to achieve your vision"] },
  { word: "Adhere", definition: "Stick to, such as with glue, or to a plan or belief", mnemonics: ["I stuck this ad-here"] },
  { word: "Admonish", definition: "Mildly scold; caution, advise, or remind to do something", mnemonics: ["If you want Monish to get free tickets, you better add Monish to the list!"] },
  { word: "Adverse", definition: "Opposing, harmful", mnemonics: ["I'm against the idea of adding a verse to this song"] },
  { word: "Advocate", definition: "Speak or argue in favor of; a person who pleads for a cause", mnemonics: ["ad (to/towards) + vocare (to speak)"] },
  { word: "Aesthetic", definition: "Concerning the appreciation of beauty or good taste", mnemonics: ["Ay! What a beautiful prosthetic!"] },
  { word: "Affable", definition: "Warm and friendly, pleasant, approachable", mnemonics: ["A friendly fellow"] },
  { word: "Affectation", definition: "Fake behavior adopted to give a certain impression", mnemonics: ["Don't want people to think I have a Ben Affleck-tation"] },
  { word: "Aggrandize", definition: "Make greater; exaggerate", mnemonics: ["Before glasses, now lasik - a-grand-eyes!"] },
  { word: "Aggregate", definition: "Gather together", mnemonics: ["Greg keeps adding more crap to his gate"] },
  { word: "Alacrity", definition: "Cheerful or speedy willingness", mnemonics: ["I lack pity for myself, so I will complete this task with alacrity!"] },
  { word: "Alienate", definition: "Cause to become unfriendly, hostile, or distant", mnemonics: ["Unfriendly like the Alien in Alien"] },
  { word: "Alleviate", definition: "Lessen, make easier to endure", mnemonics: ["This is what Aleve's marketing team was thinking about"] },
  { word: "Ambiguous", definition: "Not clear, hard to understand, open to multiple interpretations", mnemonics: ["If unclear whether you're talking about U or US, you're being ambiguous"] },
  { word: "Ambivalent", definition: "Uncertain; unable to decide or wanting contradictory things", mnemonics: ["I am ambivalent about bivalent chromosomes"] },
  { word: "Analogous", definition: "Comparable, corresponding in some particular way", mnemonics: [] },
  { word: "Anarchy", definition: "Absence of law or government; chaos, disorder", mnemonics: ["Without + king (monarch)"] },
  { word: "Anoint", definition: "Rub or sprinkle oil on; make sacred", mnemonics: ["Sprinkle an oint(ment) on"] },
  { word: "Anomaly", definition: "Deviation from what is common; inconsistency", mnemonics: ["Not + normally"] },
  { word: "Antagonize", definition: "Make hostile or unfriendly", mnemonics: ["Ants agonize over how hostile grasshoppers are"] },
  { word: "Antipathy", definition: "Deep dislike, aversion, or repugnance", mnemonics: ["I hate trails and walkways. I am anti-path-y"] },
  { word: "Apathy", definition: "Not caring; absence of feeling; lack of interest", mnemonics: ["Dog has no apathy for park rules"] },
  { word: "Apocryphal", definition: "Of questionable authenticity; false", mnemonics: ["Saying Jesus invented the Internet is apocryphal"] },
  { word: "Appease", definition: "Pacify, satisfy, relieve; concede to demands", mnemonics: ["Apps ease the assistant from difficult demands"] },
  { word: "Appreciable", definition: "Enough to be perceived, considerable", mnemonics: ["Enough to be appreciated"] },
  { word: "Arbitrary", definition: "Based entirely on one's discretion; capricious", mnemonics: ["Children tired of father's arbitrary rules, like eating Arby's every Tuesday"] },
  { word: "Arcane", definition: "Known or understood by only a few; obscure, secret", mnemonics: ["Tarot cards divided into major and minor arcana"] },
  { word: "Archaic", definition: "Characteristic of an earlier period; ancient, primitive", mnemonics: ["Really old, like a bridge with an arch under it"] },
  { word: "Arduous", definition: "Very difficult, strenuous; severe, hard to endure", mnemonics: ["Arduous rearranges to Sudor (sweat in Spanish)"] },
  { word: "Articulate", definition: "Using language in clear, fluent way; speak distinctly", mnemonics: ["An article can articulate obscure subjects"] },
  { word: "Artifact", definition: "Any object made by humans, especially from earlier times", mnemonics: ["If art is old enough, the art-in-fact becomes an artifact"] },
  { word: "Artless", definition: "Free of deceit or craftiness, natural, genuine", mnemonics: ["Francis of Assisi became artless after spiritual awakening"] },
  { word: "Ascertain", definition: "Find out with certainty", mnemonics: ["I cannot be as certain until I ascertain"] },
  { word: "Ascetic", definition: "Abstinent or austere in lifestyle", mnemonics: ["The monk had an asset-tic, an encouraging bug friend"] },
  { word: "Assuage", definition: "Make milder, relieve; soothe, pacify, calm", mnemonics: ["Garfield assuages his anxiety with sausage", "Assuage sounds like massage"] },
  { word: "Audacious", definition: "Very bold or brave, often in a rude or reckless way", mnemonics: ["That Audi driver cut me off, how Audacious"] },
  { word: "Augment", definition: "Make larger", mnemonics: ["Think breast augmentation"] },
  { word: "Austere", definition: "Strict, stern, severe", mnemonics: ["Rules imposed on Greece were called Austerity measures"] },
  { word: "Autonomous", definition: "Self-governing, independent", mnemonics: ["Self-driving (autonomous) cars"] },
  { word: "Aver", definition: "Declare or affirm with confidence", mnemonics: ["I swear I'm a ver(y nice person)"] },
  { word: "Avid", definition: "Enthusiastic, dedicated, passionate", mnemonics: ["Avid reader, avid gamer"] },
  { word: "Balk", definition: "Refuse to proceed or to do something", mnemonics: ["Picture Balki from Perfect Strangers refusing to go forward"] },
  { word: "Base", definition: "Morally low, mean, dishonorable; little value", mnemonics: ["At the base level - no value"] },
  { word: "Belie", definition: "Contradict or misrepresent", mnemonics: ["To be lying"] },
  { word: "Benign", definition: "Harmless; favorable; kind, gentle, or beneficial", mnemonics: [] },
  { word: "Bogus", definition: "Fake, fraudulent", mnemonics: ["Poor Bogut got nailed with a bogus foul"] },
  { word: "Bolster", definition: "Strengthen or support", mnemonics: [] },
  { word: "Boor", definition: "Rude, ill-mannered, or insensitive person", mnemonics: [] },
  { word: "Buffer", definition: "Something that shields, protects, absorbs shock, or cushions", mnemonics: [] },
  { word: "Bureaucracy", definition: "Government characterized by many bureaus and petty administrators", mnemonics: [] },
  { word: "Burgeon", definition: "Grow or flourish rapidly; put forth buds or shoots", mnemonics: [] },
  { word: "Buttress", definition: "Support or encourage; a structural support", mnemonics: [] },
  { word: "Bygone", definition: "Past, former", mnemonics: [] },
  { word: "Cacophony", definition: "Harsh, discordant, or meaningless mixture of sounds", mnemonics: ["Caco means caca (poop), phony means sound. Shit sound"] },
  { word: "Candid", definition: "Open, sincere, honest", mnemonics: [] },
  { word: "Canonical", definition: "Authorized, recognized; pertaining to the canon", mnemonics: [] },
  { word: "Capricious", definition: "Acting on impulse, erratic", mnemonics: ["Gambling girl in capri pants sure is capricious"] },
  { word: "Cartography", definition: "Map-making", mnemonics: [] },
  { word: "Castigate", definition: "Criticize severely; punish in order to correct", mnemonics: [] },
  { word: "Catalyst", definition: "Causer of change", mnemonics: [] },
  { word: "Caustic", definition: "Capable of corroding metal or burning skin; very critical", mnemonics: [] },
  { word: "Censure", definition: "Strong disapproval or official reprimand", mnemonics: [] },
  { word: "Chauvinism", definition: "Fanatical patriotism or blind enthusiasm for military glory", mnemonics: [] },
  { word: "Chronological", definition: "Arranged in or relating to time order", mnemonics: [] },
  { word: "Clamor", definition: "Noisy uproar or protest; loud, continuous noise", mnemonics: [] },
  { word: "Clinch", definition: "Make final or settle conclusively; fasten together", mnemonics: [] },
  { word: "Coalesce", definition: "Come together, unite; fuse together", mnemonics: ["Think koala"] },
  { word: "Cogent", definition: "Very convincing, logical", mnemonics: [] },
  { word: "Commensurate", definition: "Same in size, extent; equivalent; proportional", mnemonics: [] },
  { word: "Complacent", definition: "Self-satisfied, smug; overly content", mnemonics: [] },
  { word: "Complementary", definition: "Completing; fitting together well; filling mutual needs", mnemonics: [] },
  { word: "Compliant", definition: "Obeying, submissive; following requirements", mnemonics: [] },
  { word: "Concede", definition: "Give in, admit, yield; acknowledge reluctantly", mnemonics: [] },
  { word: "Conciliatory", definition: "Reconciling, appeasing, attempting to make peace", mnemonics: [] },
  { word: "Concur", definition: "Approve, agree", mnemonics: [] },
  { word: "Condone", definition: "Overlook, tolerate, regard as harmless", mnemonics: [] },
  { word: "Confer", definition: "Consult, compare views; bestow or give", mnemonics: ["Conference room - consult and compare views"] },
  { word: "Connoisseur", definition: "Expert, especially in the fine arts; educated, refined tastes", mnemonics: [] },
  { word: "Console", definition: "Lessen suffering or grief; control panel or small cabinet", mnemonics: [] },
  { word: "Consolidate", definition: "Unite, combine, solidify; make coherent", mnemonics: [] },
  { word: "Constrict", definition: "Squeeze, compress; restrict freedom", mnemonics: ["Boa constrictor snake"] },
  { word: "Construe", definition: "Interpret or translate", mnemonics: [] },
  { word: "Contentious", definition: "Controversial; prone to causing petty arguments", mnemonics: ["Same latin root as contender"] },
  { word: "Contextualize", definition: "Place in context by giving background or circumstances", mnemonics: [] },
  { word: "Conundrum", definition: "Riddle or mystery with answer involving wordplay", mnemonics: [] },
  { word: "Converge", definition: "Move towards one another or towards a point; unite", mnemonics: [] },
  { word: "Conversant", definition: "Knowledgeable about or experienced with", mnemonics: [] },
  { word: "Conversely", definition: "In opposite way; on the other hand", mnemonics: [] },
  { word: "Convoluted", definition: "Twisted; very complicated", mnemonics: [] },
  { word: "Copious", definition: "Plentiful, bountiful", mnemonics: [] },
  { word: "Corroborate", definition: "Support, add evidence to", mnemonics: [] },
  { word: "Cosmopolitan", definition: "Belonging to entire world; free from local prejudices", mnemonics: [] },
  { word: "Countenance", definition: "Facial expression or face; approve or tolerate", mnemonics: ["I can count ten ants if you stop making that face"] },
  { word: "Counterintuitive", definition: "Against what one would intuitively expect", mnemonics: [] },
  { word: "Counterpoint", definition: "Contrasting item, opposite; complement or contrast in art", mnemonics: [] },
  { word: "Counterproductive", definition: "Having opposite results to what was expected", mnemonics: [] },
  { word: "Covert", definition: "Secret, veiled, undercover", mnemonics: [] },
  { word: "Crafty", definition: "Cunning, skillful in deception or underhand schemes", mnemonics: [] },
  { word: "Craven", definition: "Very cowardly, lacking courage", mnemonics: ["Cowardly raven"] },
  { word: "Credibility", definition: "Believability, trustworthiness", mnemonics: [] },
  { word: "Credulous", definition: "Gullible; prone to believing too easily", mnemonics: [] },
  { word: "Crescendo", definition: "Steady increase in force, intensity; climactic moment", mnemonics: [] },
  { word: "Culminate", definition: "Reach highest point or final stage", mnemonics: ["Hard to Calm Nate when things culminate"] },
  { word: "Cynical", definition: "Thinking worst of others; bitterly pessimistic", mnemonics: [] },
  { word: "Daunt", definition: "Discourage, dishearten, lessen courage", mnemonics: ["D aunt who is intimidating scares you"] },
  { word: "Debase", definition: "Degrade; lower in quality, value, rank; lower morally", mnemonics: ["Can't reach peak of Mt. Everest, go back to De base!"] },
  { word: "Debunk", definition: "Expose, ridicule, or disprove false claims", mnemonics: [] },
  { word: "Decorous", definition: "Behaving with propriety and good taste; polite", mnemonics: ["Good decor (tasteful decoration) is decorous!"] },
  { word: "Deem", definition: "Judge; consider", mnemonics: ["If it seems good enough, deem it good enough!"] },
  { word: "Deface", definition: "Vandalize, mar the appearance", mnemonics: ["Picture scratching off the face of a clock"] },
  { word: "Defamatory", definition: "Slanderous, injurious to reputation", mnemonics: ["I want to de-fame you"] },
  { word: "Default", definition: "Failure to act, neglect; fail to fulfill obligation", mnemonics: [] },
  { word: "Deference", definition: "Respectful submission; yielding to authority", mnemonics: [] },
  { word: "Deflect", definition: "Cause to curve; turn aside from straight course", mnemonics: ["Deflect sends it off to the side vs reflect sends it back"] },
  { word: "Deleterious", definition: "Harmful, unhealthful", mnemonics: ["I just deleted my health"] },
  { word: "Delineate", definition: "Mark outline of; sketch; describe in detail", mnemonics: ["To make lines around"] },
  { word: "Denigrate", definition: "Belittle, attack reputation", mnemonics: [] },
  { word: "Denote", definition: "Be name or symbol for; sign or indication", mnemonics: ["Like a note that represents something else"] },
  { word: "Deride", definition: "Mock, scoff at, laugh at contemptuously", mnemonics: ["If your ride looks like de ride I drive, you'll get derided"] },
  { word: "Derivative", definition: "Derived from something else; not original", mnemonics: [] },
  { word: "Desiccate", definition: "Thoroughly dried up, dehydrated", mnemonics: ["DESICCANT SILICA GEL in shoe boxes keeps things dry"] },
  { word: "Detached", definition: "Impartial, disinterested; unconcerned, distant, aloof", mnemonics: ["Dis-attached, it isn't attached"] },
  { word: "Deterrent", definition: "Something that restrains or discourages", mnemonics: [] },
  { word: "Diatribe", definition: "Bitter, abusive attack or criticism; rant", mnemonics: ["A lawyer going off on a real rant"] },
  { word: "Didactic", definition: "Intended to instruct; teaching or moral lesson", mnemonics: ["Why do you have to be so didactic? (when parent lectures)"] },
  { word: "Digress", definition: "Go off-topic when speaking or writing", mnemonics: ["Forgive me, I digress - every time you go off topic"] },
  { word: "Din", definition: "Loud, confused noise, especially for long period", mnemonics: ["Din, din, din, like a ringing bell"] },
  { word: "Disabuse", definition: "Free someone from mistake in thinking", mnemonics: ["Dis is negative prefix; remove an abuse or mistake"] },
  { word: "Discerning", definition: "Having good judgement or insight; able to distinguish", mnemonics: [] },
  { word: "Discredit", definition: "Injure reputation, destroy credibility", mnemonics: ["Remove the credit"] },
  { word: "Discrepancy", definition: "Difference or inconsistency", mnemonics: ["Dis crap on my pants wasn't there before - must be discrepancy"] },
  { word: "Discriminating", definition: "Judicious, discerning, having good judgement", mnemonics: [] },
  { word: "Disingenuous", definition: "Insincere, not genuine", mnemonics: ["Not genuine"] },
  { word: "Disinterested", definition: "Unbiased, impartial; not interested", mnemonics: ["No interested"] },
  { word: "Disjointed", definition: "Disconnected, not coherent, jerky", mnemonics: ["Not joined: Joints connect things"] },
  { word: "Dismiss", definition: "Allow to disperse or leave; fire from job", mnemonics: [] },
  { word: "Dispassionate", definition: "Unbiased, not having selfish motivation; calm", mnemonics: ["Not passionate"] },
  { word: "Dispatch", definition: "Speed, promptness; send off or deal speedily", mnemonics: ["911 dispatcher sends ambulances promptly"] },
  { word: "Disperse", definition: "Scatter, spread widely, cause to vanish", mnemonics: [] },
  { word: "Disposition", definition: "Person's general or natural mood; tendency", mnemonics: [] },
  { word: "Disquieting", definition: "Disturbing, cause anxiety", mnemonics: ["Not quieting"] },
  { word: "Disseminate", definition: "Scatter, spread about, broadcast", mnemonics: [] },
  { word: "Dissent", definition: "Disagree or take opposing view", mnemonics: ["Not assent"] },
  { word: "Dissonance", definition: "Harsh, inharmonious sound; disagreement", mnemonics: ["Not sonance - not nice sounding"] },
  { word: "Distill", definition: "Purify; extract essential elements", mnemonics: [] },
  { word: "Diverge", definition: "Differ, deviate; branch off or turn aside", mnemonics: [] },
  { word: "Divest", definition: "Deprive or strip of rank, title; sell off holdings", mnemonics: [] },
  { word: "Divine", definition: "Discover through divination; perceive by insight", mnemonics: [] },
  { word: "Document", definition: "Support with evidence, cite sources in detail", mnemonics: [] },
  { word: "Dogma", definition: "System of principles laid down by authority", mnemonics: [] },
  { word: "Dormant", definition: "Asleep, inactive, on a break", mnemonics: [] },
  { word: "Dubious", definition: "Doubtful, questionable, suspect", mnemonics: [] },
  { word: "Eccentric", definition: "Peculiar, odd, deviating from norm", mnemonics: [] },
  { word: "Eclectic", definition: "Selecting best of everything from diverse sources", mnemonics: ["Similar to ELECT"] },
  { word: "Eclipse", definition: "Obscuring of one thing by another; overshadow", mnemonics: [] },
  { word: "Efficacy", definition: "Quality of being able to produce intended effect", mnemonics: ["EFFicacy = EFFective"] },
  { word: "Egalitarian", definition: "Related to belief in equality of all people", mnemonics: ["4 + 4 egals 8"] },
  { word: "Egregious", definition: "Extraordinarily or conspicuously bad; glaring", mnemonics: ["Greg isn't a little bit bad, he's extra-terribly bad"] },
  { word: "Elated", definition: "Very happy, in high spirits", mnemonics: [] },
  { word: "Elevate", definition: "Raise, lift up; lift spirits; move to higher rank", mnemonics: [] },
  { word: "Elicit", definition: "Call forth, bring out, evoke", mnemonics: ["Explicit elicits various warnings"] },
  { word: "Eloquent", definition: "Marked by forceful, fluid, apt speech", mnemonics: [] },
  { word: "Embellish", definition: "Decorate, add ornamentation; enhance with details", mnemonics: [] },
  { word: "Eminent", definition: "Prominent, distinguished, of high rank", mnemonics: [] },
  { word: "Empirical", definition: "Coming from or based on experience or experimentation", mnemonics: [] },
  { word: "Emulate", definition: "Copy in attempt to equal or be better than", mnemonics: [] },
  { word: "Enervate", definition: "Weaken, tire", mnemonics: ["Opposite of energize. Imagine the Enervater bunny"] },
  { word: "Enhance", definition: "Raise to higher value, desirability", mnemonics: [] },
  { word: "Enigma", definition: "Puzzle, mystery, riddle; mysterious person", mnemonics: ["Why this video has 130 million views is an enigma"] },
  { word: "Entitlement", definition: "Having right to certain privileges or believing deserved", mnemonics: [] },
  { word: "Enumerate", definition: "Count or list; specify one-by-one", mnemonics: [] },
  { word: "Ephemeral", definition: "Lasting only short time, fleeting", mnemonics: [] },
  { word: "Equitable", definition: "Fair, equal, just", mnemonics: [] },
  { word: "Erratic", definition: "Inconsistent, wandering, having no fixed course", mnemonics: [] },
  { word: "Erroneous", definition: "Mistaken, improper, morally incorrect", mnemonics: ["If Moses supposes erroneously"] },
  { word: "Erudite", definition: "Scholarly, knowledgeable; possessing deep knowledge", mnemonics: [] },
  { word: "Eschew", definition: "Shun, avoid, abstain from", mnemonics: [] },
  { word: "Esoteric", definition: "Understood by or intended for only a few", mnemonics: [] },
  { word: "Estimable", definition: "Worthy of esteem, admirable; able to estimate", mnemonics: [] },
  { word: "Eulogy", definition: "Speech of praise or written work of praise", mnemonics: [] },
  { word: "Exacerbate", definition: "Make worse; inflame; irritate or embitter", mnemonics: [] },
  { word: "Exacting", definition: "Very severe in making demands; requiring attention", mnemonics: [] },
  { word: "Exculpate", definition: "Clear from guilt or blame", mnemonics: [] },
  { word: "Exhaustive", definition: "Comprehensive, thorough; accounting for all", mnemonics: [] },
  { word: "Explicit", definition: "Direct, clear, fully revealed", mnemonics: [] },
  { word: "Exponent", definition: "Person who expounds; champion or advocate", mnemonics: [] },
  { word: "Extraneous", definition: "Irrelevant; foreign, not belonging", mnemonics: [] },
  { word: "Extrapolate", definition: "Conjecture about unknown by projecting known", mnemonics: ["Extra-polite to extrapolate about new acquaintance"] },
  { word: "Facetious", definition: "Joking, humorous, especially inappropriately", mnemonics: ["Focused on face when you should think underneath"] },
  { word: "Facilitate", definition: "Make easier, help progress", mnemonics: [] },
  { word: "Fallacious", definition: "Containing fallacy or mistake in logic", mnemonics: [] },
  { word: "Fanatical", definition: "Excessively devoted or zealous in uncritical way", mnemonics: ["Short version: fan, like sports fan"] },
  { word: "Fanciful", definition: "Whimsical, capricious; imaginary", mnemonics: [] },
  { word: "Fathom", definition: "Measure depth; penetrate and discover meaning", mnemonics: [] },
  { word: "Feasible", definition: "Possible, logical or likely, suitable", mnemonics: [] },
  { word: "Fidelity", definition: "Faithfulness, loyalty; accuracy in reproducing", mnemonics: ["Fidelity Investments: faithful company entrusted with money"] },
  { word: "Figurative", definition: "Metaphorical, based on figures of speech", mnemonics: [] },
  { word: "Finesse", definition: "Extreme delicacy or subtlety; use tact", mnemonics: [] },
  { word: "Flag", definition: "Get tired, lose enthusiasm; droop", mnemonics: ["A flag droops without wind"] },
  { word: "Fleeting", definition: "Passing quickly, transitory", mnemonics: [] },
  { word: "Foment", definition: "Incite, instigate, stir up; apply medicated liquid", mnemonics: ["Ferment - to brew up unrest"] },
  { word: "Foreshadow", definition: "Indicate or suggest beforehand, presage", mnemonics: [] },
  { word: "Forfeit", definition: "Surrender or lose as result of error or crime", mnemonics: [] },
  { word: "Fortify", definition: "Strengthen, invigorate, encourage", mnemonics: [] },
  { word: "Fringe", definition: "On margin or periphery; extreme group members", mnemonics: [] },
  { word: "Frugal", definition: "Economical, thrifty; inexpensive", mnemonics: [] },
  { word: "Futile", definition: "Producing no useful result, ineffective", mnemonics: [] },
  { word: "Gainsay", definition: "Declare false, deny; oppose", mnemonics: ["Say against"] },
  { word: "Garrulous", definition: "Talkative, wordy, rambling", mnemonics: ["Garrison from South Park talks a lot"] },
  { word: "Gauche", definition: "Tactless, lacking social grace; crude", mnemonics: [] },
  { word: "Gawky", definition: "Physically awkward, especially tall skinny person", mnemonics: [] },
  { word: "Germane", definition: "Relevant and appropriate, on-topic", mnemonics: [] },
  { word: "Gist", definition: "Main idea, essence", mnemonics: [] },
  { word: "Glib", definition: "Fluent and easy in superficially insincere way", mnemonics: [] },
  { word: "Gradation", definition: "Progression or process taking place gradually", mnemonics: [] },
  { word: "Gregarious", definition: "Social, pertaining to flock or crowd", mnemonics: [] },
  { word: "Guile", definition: "Clever deceit, cunning, craftiness", mnemonics: [] },
  { word: "Hackneyed", definition: "So commonplace as to be stale; not fresh", mnemonics: [] },
  { word: "Hardy", definition: "Bold, brave; capable of withstanding hardship", mnemonics: [] },
  { word: "Haven", definition: "Harbor or port; refuge, safe place", mnemonics: [] },
  { word: "Hearken", definition: "Listen, pay attention", mnemonics: [] },
  { word: "Hedonist", definition: "Person devoted to pleasure", mnemonics: [] },
  { word: "Heterogeneous", definition: "Different in type, incongruous", mnemonics: [] },
  { word: "Hierarchy", definition: "Ranked series; classification by rank", mnemonics: [] },
  { word: "Hodgepodge", definition: "Mixture of different kinds of things, jumble", mnemonics: [] },
  { word: "Homogeneous", definition: "Of same kind; uniform throughout", mnemonics: [] },
  { word: "Hyperbole", definition: "Deliberate exaggeration for effect", mnemonics: [] },
  { word: "Idiosyncrasy", definition: "Characteristic or habit peculiar to individual", mnemonics: [] },
  { word: "Illiberality", definition: "Narrow-mindedness, bigotry; lack of generosity", mnemonics: ["ill + Liberal = anti open minded"] },
  { word: "Imminent", definition: "Ready to occur, impending", mnemonics: [] },
  { word: "Impair", definition: "Make worse, weaken", mnemonics: ["Opposite of repair"] },
  { word: "Impartial", definition: "Unbiased, fair", mnemonics: [] },
  { word: "Impede", definition: "Hold back, obstruct progress", mnemonics: [] },
  { word: "Implication", definition: "Act of implying or that which is implied", mnemonics: [] },
  { word: "Implicit", definition: "Implied, not stated directly; unquestionable", mnemonics: [] },
  { word: "Implode", definition: "Burst inward", mnemonics: [] },
  { word: "Inadvertent", definition: "Unintentional; characterized by lack of attention", mnemonics: [] },
  { word: "Incendiary", definition: "Setting on fire; arousing strife or rebellion", mnemonics: [] },
  { word: "Incentive", definition: "Something that encourages greater action", mnemonics: [] },
  { word: "Inchoate", definition: "Just begun, underdeveloped, unorganized", mnemonics: [] },
  { word: "Incipient", definition: "Just beginning; in very early state", mnemonics: [] },
  { word: "Incongruous", definition: "Out of place, inappropriate, not harmonious", mnemonics: [] },
  { word: "Inconsequential", definition: "Insignificant, unimportant; illogical", mnemonics: [] },
  { word: "Incorporate", definition: "Combine, unite; form legal corporation", mnemonics: [] },
  { word: "Indeterminate", definition: "Not fixed or determined, indefinite; vague", mnemonics: [] },
  { word: "Indifferent", definition: "Not caring, having no interest; unbiased", mnemonics: [] },
  { word: "Inform", definition: "Inspire, animate; give substance or context", mnemonics: [] },
  { word: "Ingenuous", definition: "Genuine, sincere, not holding back; naive", mnemonics: [] },
  { word: "Ingrained", definition: "Deep-rooted, forming part of essence", mnemonics: [] },
  { word: "Inherent", definition: "Existing as permanent, essential quality", mnemonics: [] },
  { word: "Innocuous", definition: "Harmless, inoffensive", mnemonics: [] },
  { word: "Intelligible", definition: "Able to be understood, clear", mnemonics: [] },
  { word: "Intractable", definition: "Difficult to control or manage; stubborn", mnemonics: [] },
  { word: "Intrepid", definition: "Fearless, brave; enduring in adversity", mnemonics: [] },
  { word: "Intrinsic", definition: "Belonging to essential nature of thing", mnemonics: [] },
  { word: "Jargon", definition: "Vocabulary specific to group; unintelligible language", mnemonics: [] },
  { word: "Jocular", definition: "Joking or given to joking; jolly, playful", mnemonics: [] },
  { word: "Judicious", definition: "Using good judgement; wise, sensible", mnemonics: ["Judge Judy can be judicious"] },
  { word: "Juncture", definition: "Critical point in time; place where things join", mnemonics: [] },
  { word: "Keen", definition: "Sharp, piercing; very perceptive or mentally sharp", mnemonics: [] },
  { word: "Kudos", definition: "Praise, honor, congratulations", mnemonics: [] },
  { word: "Lackluster", definition: "Not shiny; dull, mediocre; lacking brilliance", mnemonics: ["Lacking luster or shine"] },
  { word: "Laconic", definition: "Using few words, concise", mnemonics: ["Hemingway's prose"] },
  { word: "Lament", definition: "Mourn; express grief, sorrow, or regret", mnemonics: [] },
  { word: "Lampoon", definition: "Harsh satire; ridicule or satirize", mnemonics: [] },
  { word: "Landmark", definition: "Object that stands out for navigation; important place", mnemonics: ["Mark the land so it is noticeable"] },
  { word: "Languid", definition: "Drooping from exhaustion, sluggish, slow", mnemonics: [] },
  { word: "Lassitude", definition: "Tiredness, weariness; lazy indifference", mnemonics: ["Lassie is tired"] },
  { word: "Laudable", definition: "Worthy of praise", mnemonics: ["Praise the laud (lord)"] },
  { word: "Lavish", definition: "Abundant or giving in abundance; marked by excess", mnemonics: [] },
  { word: "Layperson", definition: "Not member of clergy or particular profession", mnemonics: ["Layman's or common man's terms"] },
  { word: "Levity", definition: "Lightness of mind or spirit; lack of seriousness", mnemonics: ["To levitate, be light"] },
  { word: "Levy", definition: "Collect tax from; wage war; enlist for military", mnemonics: [] },
  { word: "Liberal", definition: "Favorable to progress; believing in maximum freedom", mnemonics: [] },
  { word: "Libertine", definition: "Morally or sexually unrestrained person", mnemonics: [] },
  { word: "Likewise", definition: "Also, in addition; similarly, in same way", mnemonics: [] },
  { word: "Log", definition: "Keep record of; travel for certain distance", mnemonics: [] },
  { word: "Loquacious", definition: "Talkative, wordy", mnemonics: [] },
  { word: "Lucid", definition: "Clear, easy to understand; rational, sane", mnemonics: [] },
  { word: "Lull", definition: "Soothe or cause to fall asleep; quiet down", mnemonics: [] },
  { word: "Makeshift", definition: "Temporary, improvised substitute", mnemonics: [] },
  { word: "Malleable", definition: "Able to be bent, shaped, or adapted", mnemonics: ["Shape it with a mallet"] },
  { word: "Maverick", definition: "Rebel, individualist, dissenter", mnemonics: [] },
  { word: "Mendacious", definition: "Lying, habitually dishonest", mnemonics: ["Some MEN are auDACIOUS enough to lie to your face"] },
  { word: "Mercurial", definition: "Quickly and unpredictably changing moods; fickle", mnemonics: [] },
  { word: "Metamorphosis", definition: "Complete change or transformation", mnemonics: [] },
  { word: "Meticulous", definition: "Taking extreme care in details; precise, fussy", mnemonics: [] },
  { word: "Mitigate", definition: "Make less severe; lessen or moderate", mnemonics: [] },
  { word: "Modest", definition: "Humble; simple rather than showy; decent", mnemonics: [] },
  { word: "Mollify", definition: "Calm or soothe an angry person; lessen", mnemonics: [] },
  { word: "Monotony", definition: "Sameness to point of being boring; lack variation", mnemonics: [] },
  { word: "Moreover", definition: "Besides; in addition to what was just stated", mnemonics: [] },
  { word: "Mores", definition: "Customs, manners, or morals of particular group", mnemonics: [] },
  { word: "Mundane", definition: "Common, ordinary, everyday", mnemonics: [] },
  { word: "Naive", definition: "Simple and unsophisticated, lacking judgment", mnemonics: [] },
  { word: "Nascent", definition: "Coming into existence, still developing", mnemonics: [] },
  { word: "Negate", definition: "Deny or refute; make void or ineffective", mnemonics: [] },
  { word: "Net", definition: "Remaining after expenses deducted; ultimate", mnemonics: [] },
  { word: "Nevertheless", definition: "However, even so, despite that", mnemonics: [] },
  { word: "Notoriety", definition: "Ill fame; being well known for disgraceful reason", mnemonics: ["Notability of a bad variety"] },
  { word: "Novel", definition: "New, fresh, original", mnemonics: [] },
  { word: "Nuance", definition: "Subtle difference in tone, meaning, or expression", mnemonics: [] },
  { word: "Objective", definition: "Factual, related to reality; not influenced by emotion", mnemonics: [] },
  { word: "Obsequious", definition: "Servile, very compliant, fawning", mnemonics: [] },
  { word: "Obsolete", definition: "No longer in use; out of date", mnemonics: ["Obviously, it arrived SO LATE that it is obsolete"] },
  { word: "Obstinate", definition: "Stubborn or hard to control", mnemonics: ["My friend Nate is so stubborn"] },
  { word: "Obviate", definition: "Prevent, eliminate, or make unnecessary", mnemonics: ["Elimin-ate what's ob-vious"] },
  { word: "Occult", definition: "Supernatural; pertaining to magic; mysterious", mnemonics: ["Black magic is a cult"] },
  { word: "Offhand", definition: "Casual, informal; done without preparation", mnemonics: [] },
  { word: "Officious", definition: "Excessively eager with unwanted advice", mnemonics: ["You give awful advice!"] },
  { word: "Offset", definition: "Counteract, compensate for", mnemonics: [] },
  { word: "Onerous", definition: "Burdensome, oppressive, hard to endure", mnemonics: [] },
  { word: "Opaque", definition: "Not translucent; dark, dull, unclear", mnemonics: [] },
  { word: "Optimal", definition: "Best, most desirable or favorable", mnemonics: [] },
  { word: "Orthodox", definition: "Adhering to traditional, established faith", mnemonics: [] },
  { word: "Oscillate", definition: "Swing back and forth; waver, change mind", mnemonics: [] },
  { word: "Outstrip", definition: "Surpass, exceed; be larger or better than", mnemonics: [] },
  { word: "Overshadow", definition: "Cast shadow over; dominate, make less important", mnemonics: [] },
  { word: "Paradigm", definition: "Model or pattern; worldview or shared assumptions", mnemonics: [] },
  { word: "Paradox", definition: "Contradiction that is actually true", mnemonics: [] },
  { word: "Pariah", definition: "Social outcast, untouchable", mnemonics: [] },
  { word: "Partial", definition: "Biased, prejudiced; having special liking", mnemonics: [] },
  { word: "Partisan", definition: "Devoted to particular group; fervent supporter", mnemonics: [] },
  { word: "Patent", definition: "Obvious, apparent, plain to see", mnemonics: [] },
  { word: "Pathological", definition: "Relating to or caused by disease", mnemonics: [] },
  { word: "Patronizing", definition: "Condescending, treating as inferior", mnemonics: [] },
  { word: "Paucity", definition: "Scarcity, state of being small in number", mnemonics: [] },
  { word: "Peccadillo", definition: "Small sin or fault", mnemonics: [] },
  { word: "Pedestrian", definition: "Ordinary, dull, commonplace", mnemonics: [] },
  { word: "Penchant", definition: "Liking or inclination", mnemonics: ["Be enchanted by = to like it"] },
  { word: "Perfidious", definition: "Disloyal, treacherous, violating trust", mnemonics: ["Opposite of perfect+fidelious = Unfaithful"] },
  { word: "Peripheral", definition: "Relating to outer boundary; not primary", mnemonics: [] },
  { word: "Permeate", definition: "Spread or penetrate throughout", mnemonics: [] },
  { word: "Pervasive", definition: "Tending to spread throughout", mnemonics: [] },
  { word: "Philanthropy", definition: "Efforts to improve well-being through giving", mnemonics: [] },
  { word: "Phony", definition: "Fake, counterfeit; insincere, not genuine", mnemonics: [] },
  { word: "Pious", definition: "Devout; religiously reverent and dutiful", mnemonics: [] },
  { word: "Pith", definition: "Core, essence; significance or weight", mnemonics: [] },
  { word: "Placate", definition: "Satisfy or calm down an angry person", mnemonics: [] },
  { word: "Placid", definition: "Peaceful, calm, tranquil", mnemonics: [] },
  { word: "Plastic", definition: "Able to be shaped or formed; easily influenced", mnemonics: [] },
  { word: "Plausible", definition: "Believable; having appearance of truth", mnemonics: [] },
  { word: "Plummet", definition: "Plunge, fall straight down", mnemonics: [] },
  { word: "Polarized", definition: "Divided into sharply opposed groups", mnemonics: [] },
  { word: "Ponderous", definition: "Heavy, bulky and unwieldy; dull, labored", mnemonics: [] },
  { word: "Posthumous", definition: "Happening or continuing after death", mnemonics: [] },
  { word: "Potentate", definition: "Ruler, person of great power", mnemonics: ["Potent = powerful"] },
  { word: "Pragmatic", definition: "Practical; dealing with actual facts", mnemonics: [] },
  { word: "Preamble", definition: "Introductory statement, preface", mnemonics: [] },
  { word: "Precarious", definition: "Unstable, insecure, dangerous", mnemonics: [] },
  { word: "Precursor", definition: "Something that comes before; announces something", mnemonics: [] },
  { word: "Predisposed", definition: "Having inclination or tendency beforehand", mnemonics: [] },
  { word: "Preempt", definition: "Prevent; take place of; take before others", mnemonics: [] },
  { word: "Presumptive", definition: "Based on inference or assumption", mnemonics: [] },
  { word: "Presumptuous", definition: "Too bold or forward; going beyond proper", mnemonics: [] },
  { word: "Pretentious", definition: "Claiming importance unjustified; showing off", mnemonics: [] },
  { word: "Principled", definition: "Having high moral standards", mnemonics: [] },
  { word: "Pristine", definition: "In original, pure state; uncorrupted", mnemonics: [] },
  { word: "Probity", definition: "Honesty, integrity", mnemonics: [] },
  { word: "Prodigal", definition: "Wasteful, extravagant; giving abundantly", mnemonics: ["The Prodigal son"] },
  { word: "Prodigious", definition: "Extraordinarily large, impressive", mnemonics: [] },
  { word: "Profligate", definition: "Completely immoral; extremely wasteful", mnemonics: [] },
  { word: "Profound", definition: "Very insightful; pervasive, intense", mnemonics: [] },
  { word: "Profuse", definition: "Abundant, extravagant; giving freely", mnemonics: [] },
  { word: "Prohibitive", definition: "Tending to forbid; serving to prevent", mnemonics: [] },
  { word: "Proliferate", definition: "Increase or spread rapidly or excessively", mnemonics: [] },
  { word: "Prologue", definition: "Introductory part to book or play", mnemonics: [] },
  { word: "Pronounced", definition: "Distinct, strong, clearly indicated", mnemonics: [] },
  { word: "Propriety", definition: "Conforming to good manners or appropriate behavior", mnemonics: [] },
  { word: "Prosaic", definition: "Dull, ordinary", mnemonics: ["Prosaic sounds interesting but means dull"] },
  { word: "Proscribe", definition: "Prohibit, outlaw; denounce; exile", mnemonics: [] },
  { word: "Prospective", definition: "Potential, in future", mnemonics: [] },
  { word: "Prudent", definition: "Wise in practical matters; providing for future", mnemonics: [] },
  { word: "Pugnacious", definition: "Inclined to fight, combative", mnemonics: ["Pugs are ready to fight!"] },
  { word: "Qualified", definition: "Modified, limited, conditional", mnemonics: [] },
  { word: "Quandary", definition: "Uncertainty or confusion about what to do", mnemonics: ["Quandary or Laundry? I am so confused!"] },
  { word: "Quibble", definition: "Make trivial arguments or criticism", mnemonics: [] },
  { word: "Quotidian", definition: "Daily; everyday, ordinary", mnemonics: [] },
  { word: "Ranks", definition: "Personnel; group of people considered together", mnemonics: [] },
  { word: "Reap", definition: "Harvest; gather; get as result of effort", mnemonics: [] },
  { word: "Recluse", definition: "Person who lives in seclusion", mnemonics: [] },
  { word: "Refute", definition: "Prove to be false", mnemonics: [] },
  { word: "Relegate", definition: "Send to inferior place, rank; exile", mnemonics: [] },
  { word: "Remedial", definition: "Providing remedy, curative; correcting deficiency", mnemonics: [] },
  { word: "Render", definition: "Give, submit, surrender; translate", mnemonics: [] },
  { word: "Replete", definition: "Supplied in abundance, filled", mnemonics: [] },
  { word: "Reproach", definition: "Blame, disgrace; criticize, express disappointment", mnemonics: [] },
  { word: "Repudiate", definition: "Reject, cast off, deny authority of", mnemonics: [] },
  { word: "Requite", definition: "Reciprocate, repay, or revenge", mnemonics: [] },
  { word: "Rescind", definition: "Annul, repeal, make void", mnemonics: [] },
  { word: "Resolution", definition: "Quality of being firmly determined; formal judgment", mnemonics: [] },
  { word: "Resolve", definition: "Find solution; firmly decide; decide by vote", mnemonics: [] },
  { word: "Respectively", definition: "In order given", mnemonics: [] },
  { word: "Restive", definition: "Impatient or uneasy under control; resisting", mnemonics: [] },
  { word: "Reticent", definition: "Not talking much; private, restrained, reserved", mnemonics: ["I'll give you a cent for your thoughts - No I don't want to share"] },
  { word: "Retrospective", definition: "Looking to past or backward; retroactive", mnemonics: [] },
  { word: "Reverent", definition: "Feeling or expressing very deep respect and awe", mnemonics: [] },
  { word: "Rhetoric", definition: "Art of persuasion through speaking; elaborate language", mnemonics: [] },
  { word: "Rife", definition: "Happening frequently, abundant", mnemonics: [] },
  { word: "Rudimentary", definition: "Elementary, relating to basics; underdeveloped", mnemonics: [] },
  { word: "Rustic", definition: "Relating to country life; primitive; rural", mnemonics: [] },
  { word: "Sacrosanct", definition: "Sacred, inviolable, not to be violated", mnemonics: ["Sacred saint = most holy"] },
  { word: "Sagacious", definition: "Wise; showing good judgement and foresight", mnemonics: [] },
  { word: "Salubrious", definition: "Healthful, promoting health", mnemonics: ["Salud! to your health!"] },
  { word: "Sanction", definition: "Permission or approval; allow, confirm", mnemonics: [] },
  { word: "Sanguine", definition: "Cheerfully optimistic, hopeful; reddish, ruddy", mnemonics: [] },
  { word: "Sap", definition: "Inner fluid of plant; energy; weaken", mnemonics: [] },
  { word: "Satiate", definition: "Fully satisfy; beyond satisfying to excess", mnemonics: [] },
  { word: "Saturate", definition: "Soak or imbue thoroughly", mnemonics: [] },
  { word: "Savor", definition: "Appreciate fully, taste or smell with pleasure", mnemonics: [] },
  { word: "Scant", definition: "Not enough or barely enough", mnemonics: [] },
  { word: "Scathing", definition: "Severe, injurious; bitterly harsh or critical", mnemonics: [] },
  { word: "Secular", definition: "Not religious or holy; pertaining to worldly", mnemonics: [] },
  { word: "Sedulous", definition: "Persevering, persistent, diligent", mnemonics: [] },
  { word: "Sentient", definition: "Conscious; experiencing sensation or perceiving", mnemonics: [] },
  { word: "Simultaneous", definition: "At same time", mnemonics: [] },
  { word: "Skeptic", definition: "Person inclined to doubting generally accepted beliefs", mnemonics: [] },
  { word: "Skirt", definition: "Border, lie along edge; evade", mnemonics: [] },
  { word: "Slack", definition: "Loose, negligent, lazy; neglect duties", mnemonics: [] },
  { word: "Slew", definition: "Large number or quantity", mnemonics: [] },
  { word: "Slight", definition: "Small, not important; treat as unimportant", mnemonics: [] },
  { word: "Solicitous", definition: "Concerned or anxious; expressing care; eager", mnemonics: [] },
  { word: "Soporific", definition: "Causing sleep; sleepy, drowsy", mnemonics: [] },
  { word: "Sound", definition: "Measure depth; penetrate and discover meaning", mnemonics: [] },
  { word: "Spartan", definition: "Very disciplined and stern; frugal, austere", mnemonics: [] },
  { word: "Spate", definition: "Sudden outpouring or rush; flood", mnemonics: [] },
  { word: "Spearhead", definition: "Be the leader of", mnemonics: [] },
  { word: "Specious", definition: "Seemingly true but actually false", mnemonics: [] },
  { word: "Spectrum", definition: "Broad range of related qualities or ideas", mnemonics: [] },
  { word: "Speculate", definition: "Contemplate; make educated guess; gamble", mnemonics: [] },
  { word: "Sporadic", definition: "Occasional, happening irregularly or scattered", mnemonics: [] },
  { word: "Sportive", definition: "Playful, merry, joking around", mnemonics: ["Daniel is on Tinder for sportive reasons"] },
  { word: "Standing", definition: "Status, rank, reputation; existing indefinitely", mnemonics: [] },
  { word: "Stark", definition: "Complete, total, utter; harsh; extremely simple", mnemonics: [] },
  { word: "Static", definition: "Fixed, not moving or changing; lacking vitality", mnemonics: [] },
  { word: "Status quo", definition: "Existing state or condition", mnemonics: [] },
  { word: "Stingy", definition: "Not generous with money, reluctant to give", mnemonics: [] },
  { word: "Stoic", definition: "Indifferent to pleasure or pain; enduring without complaint", mnemonics: [] },
  { word: "Stolid", definition: "Unemotional, showing little emotion", mnemonics: ["Like stoic + solid - not moving"] },
  { word: "Stymie", definition: "Block, hinder, or thwart; an obstacle", mnemonics: [] },
  { word: "Subjective", definition: "Existing in mind; personal, based on feelings", mnemonics: [] },
  { word: "Subside", definition: "Sink, settle down; become less active", mnemonics: [] },
  { word: "Substantiate", definition: "Support with evidence or proof", mnemonics: [] },
  { word: "Succeeding", definition: "Coming after or following", mnemonics: [] },
  { word: "Supersede", definition: "Replace, take position of; cause to be obsolete", mnemonics: [] },
  { word: "Supplicate", definition: "Pray humbly; ask, beg, or seek humbly", mnemonics: [] },
  { word: "Surfeit", definition: "Excess, excessive amount, overindulgence", mnemonics: [] },
  { word: "Surmise", definition: "Guess, infer; make opinion with incomplete info", mnemonics: [] },
  { word: "Sycophant", definition: "Servile flatterer, parasitic person", mnemonics: ["Imagine a psycho-ant telling you how great you are", "Sick parasite"] },
  { word: "Synchronous", definition: "Happening at same time; occurring at same rate", mnemonics: [] },
  { word: "Table", definition: "Lay aside to discuss later; postpone indefinitely", mnemonics: [] },
  { word: "Tacit", definition: "Understood without being said; implied", mnemonics: [] },
  { word: "Taciturn", definition: "Reserved or uncommunicative in speech; saying little", mnemonics: [] },
  { word: "Tangential", definition: "Only slightly relevant, going off topic", mnemonics: [] },
  { word: "Temperance", definition: "Moderation, self-control; total abstinence", mnemonics: [] },
  { word: "Tenuous", definition: "Long and thin, slender; flimsy; having little substance", mnemonics: [] },
  { word: "Timely", definition: "Well-timed, happening at suitable time", mnemonics: [] },
  { word: "Timorous", definition: "Fearful, timid", mnemonics: ["Timid Tim"] },
  { word: "Tirade", definition: "Bitter, abusive criticism or verbal attack", mnemonics: [] },
  { word: "Torpor", definition: "Sluggishness, lethargy, apathy", mnemonics: ["Torpor = torpedo slow moving"] },
  { word: "Torrid", definition: "Very hot, parching, burning; passionate", mnemonics: ["Torrid = torch burning flame"] },
  { word: "Tractable", definition: "Easily controlled or managed, docile", mnemonics: [] },
  { word: "Transitory", definition: "Temporary, short-lived, not lasting", mnemonics: [] },
  { word: "Trifling", definition: "Trivial, not important; frivolous, shallow", mnemonics: [] },
  { word: "Trite", definition: "Lacking freshness and originality; cliche", mnemonics: ["Miss-spelled store names like Rite-Aid are Trite"] },
  { word: "Ubiquitous", definition: "Existing everywhere at same time", mnemonics: [] },
  { word: "Undermine", definition: "Weaken, cause to collapse by digging", mnemonics: [] },
  { word: "Underscore", definition: "Emphasize, or literally underline text", mnemonics: [] },
  { word: "Unearth", definition: "Dig up, uncover, expose", mnemonics: ["Take off the earth that was on top"] },
  { word: "Unequivocal", definition: "Unambiguous, clear, absolute", mnemonics: [] },
  { word: "Unprecedented", definition: "Never before known or seen", mnemonics: [] },
  { word: "Unseemly", definition: "Improper, inappropriate; against rules of taste", mnemonics: [] },
  { word: "Vacillate", definition: "Waver in mind or opinions, be indecisive", mnemonics: [] },
  { word: "Venerate", definition: "Revere, regard with deep respect and awe", mnemonics: ["Only venerate things that are truly great"] },
  { word: "Veracity", definition: "Truthfulness, accuracy; adherence to truth", mnemonics: ["Ver comes from latin for truth"] },
  { word: "Verbose", definition: "Wordy", mnemonics: ["Using a lot of verbs"] },
  { word: "Viable", definition: "Capable of living or growing; practical, workable", mnemonics: ["If it is viable, it is able to live"] },
  { word: "Vintage", definition: "Related to items of high quality from previous era", mnemonics: ["Originally related to wine; age increases value"] },
  { word: "Virtual", definition: "Existing only in mind or by computer network", mnemonics: [] },
  { word: "Vituperate", definition: "Verbally abuse, rebuke or criticize harshly", mnemonics: ["If you don't cooperate, I will vituperate"] },
  { word: "Volatile", definition: "Varying, inconsistent; tending to violence", mnemonics: ["From latin for to fly; could fly off at any moment"] },
  { word: "Warranted", definition: "Justified, authorized", mnemonics: ["Success of Warrant (band) wasn't really justified"] },
  { word: "Wary", definition: "Watchful, motivated by caution; on guard", mnemonics: ["Waiting for something scARY"] },
  { word: "Whereas", definition: "While on contrary, considering that", mnemonics: [] },
  { word: "Whimsical", definition: "Marked by whims; erratic, unpredictable", mnemonics: ["Musical with characters riding bicycles on ice eating popsicles"] },
  { word: "Wily", definition: "Crafty, cunning; characterized by tricks", mnemonics: ["Wile E. Coyote"] },
  { word: "Zeal", definition: "Great fervor or enthusiasm for cause", mnemonics: ["Crowd going crazy at Zoo watching a seal"] },
  { word: "Zenith", definition: "High point, culmination", mnemonics: ["High point of Zenith TVs was 1990s fat-back TV era"] }
];

// Export for use in main app
if (typeof module !== 'undefined' && module.exports) {
  module.exports = VOCAB_DATA;
}
