// GRE Vocabulary Data - Essential List
// Source: TestCrackers GRE Word List
// 502 core GRE vocabulary words

const VOCAB_ESSENTIALS = [
  { word: "Abate", definition: "(v) Reduce, Diminish, become less in amount or intensity;", mnemonics: ["Abe ate all the food...now it's all gone KP", "mosquito abatement-city sprays to kill mosquitos, abandoned vehicle abatement-city tows away abandoned cars -jlue"] },
  { word: "Abdicate", definition: "(v) Formally give up the throne (or some other power or responsibility), give up, such as power, as of monarchs and emperors, or duties and obligations", mnemonics: ["A dictate is a command; addicate is to give up the power to dictate. (ab + dicare = away + declare)", "Queen Elizabeth's uncle in the \"Crown\" series on Netflix"] },
  { word: "Aberrant", definition: "markedly different from an accepted norm,", mnemonics: ["ab + errare = away + to stray (from the normal)"] },
  { word: "Abhor", definition: "Detest, regard with disgust", mnemonics: ["If it is ABsolutely HORribble, it should be abhored", "a whore"] },
  { word: "Abjure", definition: "Give up, renounce; repudiate, recant, or shun (especially formally or under oath)", mnemonics: ["ab + jurare = away from swearing, ie moving away from what you swore", "a jury renounces media influence"] },
  { word: "Abrasive", definition: "Rough, suitable for grinding or polishing (such as sandpaper); causing irritation or annoyance", mnemonics: ["a bra can be aBRAsive"] },
  { word: "Abridge", definition: "Reduce or lessen; shorten by omitting parts throughout while retaining the main idea", mnemonics: ["a bridge allows you to omit certain important parts of the trip, like swimming across a river", "Use the bridge for a shortcut", "Yu-Gi-Oh the abridged series!"] },
  { word: "Abstain", definition: "Hold back, refrain (especially from something bad or unhealthy); decline to vote", mnemonics: ["If you don't want to strain your abs, abstain from sit-ups"] },
  { word: "Acme", definition: "Summit, peak, highest point", mnemonics: ["I think of Wile E. Coyote and Road Runner on a mountain top with the acme dynamite KP", "AsCend the Mountain to get to its Eek! (L.C.)"] },
  { word: "Activism", definition: "The practice of pursuing political or other goals through vigorous action, often including protests and demonstrations", mnemonics: ["Be ACTIVE in order to achieve your vision (of toppling the patriarchy)"] },
  { word: "Adhere", definition: "Stick (to), such as with glue, or to a plan or belief", mnemonics: ["I stuck this ad-here.", "Adam Smith-Kipnis"] },
  { word: "Admonish", definition: "Mildly scold; caution, advise, or remind to do something", mnemonics: ["You've got to stop forgetting! If you want Monish to get free tickets, you better add Monish to the list!", "we"] },
  { word: "Adverse", definition: "(adj) Opposing, harmful", mnemonics: ["I'm against the idea of adding a verse to this song; it's too long already!"] },
  { word: "Advocate", definition: "Speak or argue in favor of (verb); a person who pleads for a cause or on behalf of another person (noun)", mnemonics: ["ad (to or towards) + vocare (to speak)"] },
  { word: "Aesthetic", definition: "Concerning the appreciation of beauty or good taste, pertaining to the science of what is beautiful (adj); a sense of beauty and taste of a particular time and place (noun)", mnemonics: ["Ay! What a beautiful prosthetic!"] },
  { word: "Affable", definition: "Warm and friendly, pleasant, approachable", mnemonics: ["A friendly fellow", "Laura Caskey"] },
  { word: "Affectation", definition: "Fake behavior (such as in speech or dress) adopted to give a certain impression", mnemonics: ["I can pull of a pretty convincing Boston accent, but I try to keep it to myself so that people don't think that I have a Ben Affleck-tation"] },
  { word: "Aggrandize", definition: "Make greater; exaggerate", mnemonics: ["Before I wore glasses but I got lasik surgery so now I have a-grand-eyes!"] },
  { word: "Aggregate", definition: "gather together", mnemonics: ["Greg keeps adding more crap to his gate; what a giant combination of stuff!"] },
  { word: "Alacrity", definition: "Cheerful or Speedy willingness", mnemonics: ["I lack pity for myself, so I will complete this task with alacrity!"] },
  { word: "Alienate", definition: "Cause to become unfriendly, hostile, or distant", mnemonics: ["You know, unfriendly like the Alien in Alien."] },
  { word: "alleviate", definition: "Lessen, make easier to endure", mnemonics: ["I'm pretty sure this is what \"Aleve\"'s marketing team was thinking about when they named their product"] },
  { word: "", definition: "", mnemonics: [] },
  { word: "Ambiguous", definition: "Not clear, hard to understand, open to having several meanings of interpretations", mnemonics: ["If it is unclear whether you're talking about U or US, you're being ambiguous"] },
  { word: "Ambivalent", definition: "Uncertain; unable to decide, or wanting to do two contradictory things at once", mnemonics: ["I am ambivalent about bivalent chromosomes. Maybe they are great, maybe they aren’t, I don’t really know because I’m not sure what they do."] },
  { word: "Analogous", definition: "Comparable, corresponding in some particular way (making a good analogy)", mnemonics: [] },
  { word: "Anarchy", definition: "Absence of law or government; chaos, disorder", mnemonics: ["Without + king (monarch)"] },
  { word: "Anoint", definition: "Rub or sprinkle oil on; make sacred, such as by a ceremony that includes applying oil to someone", mnemonics: ["sprinkle an oint(ment) on"] },
  { word: "Anomaly", definition: "Deviation from what is common; inconsistency", mnemonics: ["not + normally"] },
  { word: "Antagonize", definition: "Make hostile or unfriendly", mnemonics: ["Ants agonize over how hostile and unfriendly grasshoppers are to them. Grasshoppers are constantly antagonizing them!"] },
  { word: "antipathy", definition: "Deep dislike, aversion, or repugnance, sometimes without reason", mnemonics: ["Ugg, I hate trails, routes, and walkways. They are the worst! I am anti-path-y."] },
  { word: "Apathy", definition: "Not caring; absence of feeling; lack of interest or concern", mnemonics: ["Up a path and to the left is a dog taking a poop under a ‘no dogs on the grass’ sign. That dog has no apathy for park rules."] },
  { word: "Apocryphal", definition: "Of questionable authenticity; false", mnemonics: ["Apocrypha is biblical or related writings not forming a part of the accepted canon of Scripture, but saying Jesus invented the Internet is just apocryphal!"] },
  { word: "Appease", definition: "Pacify, satisfy, relieve; concede to belligerent demands, sometimes at the expense of principles", mnemonics: ["Apps ease the overworked assistant from her difficult boss’ demands. She is able to order her employer’s fat-free, gluten-free, organic, vegan spinach protein shake on Grub Hub."] },
  { word: "Appreciable", definition: "Enough to be perceived, considerable", mnemonics: ["Enough to be appreciated"] },
  { word: "Arbitrary", definition: "Based entirely on one's discretion; capricious, unreasonable, or having no basis", mnemonics: ["The children were tired of the arbitrary rules their father made on a whim, such as that they could only eat Arby’s on every other Tuesday."] },
  { word: "Arcane", definition: "Known or understood by only a few; obscure, secret", mnemonics: ["To remember this I think about how tarot cards are divided into the major and minor arcana, and that I have no idea how to read tarot cards (so for me, they are obscure and secret knowledge)."] },
  { word: "Archaic", definition: "Characteristic of an earlier period, ancient, primitive", mnemonics: ["Really old, like a bridge with an arch under it"] },
  { word: "Arduous", definition: "Very difficult, strenuous; severe, hard to endure", mnemonics: ["You can rearrange the letters in Arduous to spell Sudor (though there is an ‘a’ and a ‘u’ left over), which means sweat in Spanish. Something arduous, such as climbing Mount Everest would make you sweat a lot."] },
  { word: "Articulate", definition: "Using language in a clear, fluent way (adj.); speak distinctly or give clarity to an idea (v)", mnemonics: ["An article in a layman’s magazine (such as Archeology Magazine) can make obscure subjects, such Acheulean stone tools, understandable and interesting to readers. Articles can articulate archeology!"] },
  { word: "Artifact", definition: "Any object made by humans, especially those form an earlier time, such as those excavated by archeologists", mnemonics: ["If a work of art is old enough, such as early cave paintings, the art-in-fact is considered more of an artifact."] },
  { word: "Artless", definition: "Free of deceit or craftiness, natural, genuine; lacking skill or knowledge, crude, uncultured", mnemonics: ["I imagine Francis of Assisi (who would become Saint Francis), the son of a silk merchant, as being a selfish and crafty teenager in his lavish home covered in fancy paintings. However, once he had a spiritual awakening he became artless, literally by selling the paintings off his walls in order to give the proceeds to the poor. He lived a genuine and humble life in crude homes with bare walls (when their was walls)."] },
  { word: "Ascertain", definition: "Find out with certainty", mnemonics: ["I cannot be as certain as you until I ascertain a few things"] },
  { word: "Ascetic", definition: "Abstinent or austere in lifestyle; a person who leads an austere and simple life without material pleasures, esp. someone who does this for religious reasons", mnemonics: ["Occasionally the monk got discouraged from his ascetic lifestyle, luckily he had an asset-tic, an encouraging bug friend who would keep him company in his sparse cave and would make chirping sounds that distracted him from hunger."] },
  { word: "Assuage", definition: "Make milder, relieve; soothe, pacify, or calm", mnemonics: ["Garfield, a habitual stress eater, assuages his anxiety with sausage KP", "assuage sounds like massage- perhaps how one's body feels after a massage- RD"] },
  { word: "Audacious", definition: "Very bold or brave, often in a rude or reckless way", mnemonics: ["‘That Audi driver to cut me off, how Audacious’"] },
  { word: "Augment", definition: "Make Larger", mnemonics: ["Think breast augmentation, the more formal way of saying boob job."] },
  { word: "Austere", definition: "", mnemonics: ["All of the rules imposed on Greece and other nations that received a bail-out from the EU were called Austerity measures"] },
  { word: "Autonomous", definition: "Self-governing, independent", mnemonics: ["The autonomous country of Italy was ruled by fascism for decades, but Ferrari and Fiat are cars, so they can’t be fascist, though they can be auto-no-mous-solini."] },
  { word: "Aver", definition: "Declare or affirm with confidence", mnemonics: ["I swear I'm a ver (y nice person)"] },
  { word: "Avid", definition: "Enthusiastic, dedicated, passionate; excessively desirous", mnemonics: ["Alvin has become too avid about avidin protein! Though he started by simply eating omelets for a boost in avidin, things have quickly escalated and he is dedicatedly drinking glasses of raw egg whites every day."] },
  { word: "Balk", definition: "Refuse to proceed or to do something", mnemonics: ["Picture Balki from Perfect Strangers getting into a bad situation and then refusing to go forward"] },
  { word: "Base", definition: "Morally low, mean, dishonorable; or little or no value; crude and unrefined; counterfeit", mnemonics: ["At the base level of something - no value"] },
  { word: "", definition: "", mnemonics: [] },
  { word: "Belie", definition: "Contradict or misrepresent", mnemonics: ["\"to be lying\""] },
  { word: "Benign", definition: "Harmless; favorable; kindle, gentle, or beneficial; not cancerous", mnemonics: [] },
  { word: "Bogus", definition: "Fake, fraudulent", mnemonics: ["Poor Bogut got nailed with a bogus foul"] },
  { word: "Bolster", definition: "Strengthen or support", mnemonics: [] },
  { word: "Boor", definition: "Rude, ill-mannered, or insensitive person a peasant or a country bumpkin", mnemonics: [] },
  { word: "Buffer", definition: "Something that shields, protects, absorbs shock, or cushions", mnemonics: [] },
  { word: "Bureaucracy", definition: "Govt. characterized be many bureaus and petty administrators or by excessive, seemingly meaningless requirements", mnemonics: [] },
  { word: "Burgeon", definition: "Grow or flourish rapidly; put forth buds or shoots (of a plant)", mnemonics: [] },
  { word: "Buttress", definition: "Support or encourage (v); a support or prop, esp. projecting from and supporting the wall of a building (n)", mnemonics: [] },
  { word: "Bygone", definition: "Past, former (adj.); that which is in the past (usually plural noun)", mnemonics: [] },
  { word: "Cacophony", definition: "Harsh, discordant, or meaningless mixture of sounds", mnemonics: ["literally, caco comes from a root meaning \"caca\" as in \"cacapoopoo\" as in shit. And phony shares a root with telephone and phonograph and means sound. So this means \"shit sound\", or \"sounds like shit.\""] },
  { word: "Candid", definition: "Open, sincere, honest", mnemonics: [] },
  { word: "Canonical", definition: "Authorized, recognized; pertaining to the canon, or body of accepted rules, standards or artistic works", mnemonics: [] },
  { word: "Capricious", definition: "Acting on impulse, erratic", mnemonics: ["gambling girl in capri pants sure is capricious"] },
  { word: "Cartography", definition: "Map-making", mnemonics: [] },
  { word: "Castigate", definition: "Criticize severely; punish in order to correct", mnemonics: [] },
  { word: "Catalyst", definition: "Causer of change", mnemonics: [] },
  { word: "Caustic", definition: "Capable of corroding metal or burning the skin; very critical or sarcastic", mnemonics: [] },
  { word: "Censure", definition: "Strong disapproval or official reprimand (n); to issue such disapproval or reprimand (v)", mnemonics: [] },
  { word: "Chauvinism", definition: "Fanatical patriotism or blind enthusiasm for military glory; undue or biased devotion to any group, cause, etc.", mnemonics: [] },
  { word: "Chronological", definition: "Arranged in or relating to time order", mnemonics: [] },
  { word: "Clamor", definition: "Noisy uproar or protest, as from a crowd; a loud, continuous noise", mnemonics: [] },
  { word: "Clinch", definition: "Make final or settle conclusively; to fasten or hold together", mnemonics: [] },
  { word: "Coalesce", definition: "Come together, unite; fuse together", mnemonics: ["think koala"] },
  { word: "Cogent", definition: "Very convincing, logical", mnemonics: [] },
  { word: "Commensurate", definition: "The same in size, extent, etc., equivalent; proportional", mnemonics: [] },
  { word: "Complacent", definition: "Self-satisfied, smug; overly content (and therefore lazy, neglectful, or some other bad quality)", mnemonics: [] },
  { word: "Complementary", definition: "Completing; fitting together well; filling mutual needs", mnemonics: [] },
  { word: "Compliant", definition: "Obeying, submissive; following the requirements", mnemonics: [] },
  { word: "Concede", definition: "Give in, admit, yield; acknowledge reluctantly; grant or give up (such as giving up land after losing a war)", mnemonics: [] },
  { word: "Conciliatory", definition: "Reconciling, appeasing, attempting to make the peace", mnemonics: [] },
  { word: "Concur", definition: "Approve, agree", mnemonics: [] },
  { word: "Condone", definition: "Overlook, tolerate, regard as harmless", mnemonics: [] },
  { word: "Confer", definition: "Consult, compare views; bestow or give", mnemonics: ["as in conference room, you consult and compare views"] },
  { word: "Connoisseur", definition: "Expert, especially in the fine arts; person or educated, redefined tastes", mnemonics: [] },
  { word: "Console", definition: "Lessen the suffering or grief of (v); a control panel, or small table or cabinet (n)", mnemonics: [] },
  { word: "Consolidate", definition: "Unite, combine, solidify; make coherent", mnemonics: [] },
  { word: "Constrict", definition: "Squeeze, compress; restrict the freedom of", mnemonics: ["boa constrictor (snake)"] },
  { word: "Construe", definition: "interpret or translate", mnemonics: [] },
  { word: "Contentious", definition: "Controversial; prone to causing arguments, especially gratuitous or petty ones", mnemonics: ["Comes from the same latin root as contender (https://www.youtube.com/watch?v=efHzGxEzDQA)"] },
  { word: "Contextualize", definition: "Place in context, such as by giving the background or circumstances", mnemonics: [] },
  { word: "Conundrum", definition: "Riddle, the answer to which involves a play on words; a mystery", mnemonics: [] },
  { word: "Converge", definition: "Move towards one another or towards a point; unite", mnemonics: [] },
  { word: "Conversant", definition: "Knowledgeable about or experienced with", mnemonics: [] },
  { word: "Conversely", definition: "in opposite way; on the other hand", mnemonics: [] },
  { word: "Convoluted", definition: "Twisted; very complicated", mnemonics: [] },
  { word: "Copious", definition: "Plentiful, bountiful", mnemonics: [] },
  { word: "Corroborate", definition: "Support, add evidence to", mnemonics: [] },
  { word: "Cosmopolitan", definition: "Belonging to the entire world, at home globally; free from local or national prejudices or attachements", mnemonics: [] },
  { word: "Countenance", definition: "Facial expression or face (n); approve or tolerate (v)", mnemonics: ["Look, there are a lot of ants here. I can count ten ants, if you stop making that face and approve or at least accept my request", "Actors must have expressive countenance"] },
  { word: "Counterintuitive", definition: "Against what one would intuitively expect", mnemonics: [] },
  { word: "Counterpoint", definition: "Contrasting item, opposite; a complement; the use of contrast or interplay in a work of art", mnemonics: [] },
  { word: "Counterproductive", definition: "Having opposite results to what was expected", mnemonics: [] },
  { word: "Covert", definition: "Secret, veiled, undercover", mnemonics: [] },
  { word: "Crafty", definition: "Cunning, skillful in deception or underhandled schemes", mnemonics: [] },
  { word: "Craven", definition: "Very cowardly, lacking courage", mnemonics: ["cowardly raven"] },
  { word: "Credibility", definition: "Believability, trustworthiness", mnemonics: [] },
  { word: "Credulous", definition: "Gullible; prone to believing or trusting too easily or without enough evidence", mnemonics: [] },
  { word: "Crescendo", definition: "Steady increase in force, intensity, or the loudness of a musical passage; a climactic moment or peak", mnemonics: [] },
  { word: "Culminate", definition: "Reach the highest point or final stage", mnemonics: ["It is hard to Calm Nate when things are about to culminate"] },
  { word: "Cynical", definition: "Thinking the worst of others' motivations; bitterly pessimistic", mnemonics: [] },
  { word: "Daunt", definition: "Discourage, dishearten, lessen the courage of", mnemonics: ["D aunt who is intimidating; daunting, who scares you"] },
  { word: "Debase", definition: "Degrade; lower in quality, value, rank, etc.; lower in moral quality", mnemonics: ["If you can't make it to the peak of Mt. Everest, go back to De base!"] },
  { word: "Debunk", definition: "Expose, ridicule, or disprove false or exaggerated claims", mnemonics: [] },
  { word: "Decorous", definition: "Behaving with propriety and good taste; polite", mnemonics: ["Good decor (tasteful decoration) is decorous!"] },
  { word: "Deem", definition: "judge; consider", mnemonics: ["If it seems good enough, deem it good enough!"] },
  { word: "Deface", definition: "Vandalize. mar the appearance of", mnemonics: ["Picture scratching off the face of a clock"] },
  { word: "Defamatory", definition: "Slanderous, injurious, to someone's reputation", mnemonics: ["I would like to take your fame away. I want to de-fame you. Like when veterinarians defang an animal, but with fame instead."] },
  { word: "Default", definition: "Failure to act, neglect (n); fail to fulfill an obligation, especially a financial one (v)", mnemonics: [] },
  { word: "Deference", definition: "Respectful submission; yielding to the authority or opinion of another", mnemonics: [] },
  { word: "Deflect", definition: "Cause to curve; turn aside, esp. from a straight course; avoid", mnemonics: ["When you reflect something you send it back in the direction it came from; when you deflect it you send it off to the side"] },
  { word: "Deleterious", definition: "Harmful, unhealthful", mnemonics: ["I just deleted my health"] },
  { word: "Delineate", definition: "Mark the outline of; sketch; describe in detail", mnemonics: ["To make lines around"] },
  { word: "Denigrate", definition: "Belittle, attack the reputation of", mnemonics: [] },
  { word: "Denote", definition: "Be a name or symbol for be a sign or indication of", mnemonics: ["think about it like a note that you leave to represent something else \"Sorry, the statue that is usually here has been removed for repair. We apologize for the inconvenience.\""] },
  { word: "Deride", definition: "mock. scoff at laugh at contemptuously", mnemonics: ["If your ride looks anything like de ride I drive, you're going to get derided everywhere you go"] },
  { word: "Derivative", definition: "Derived from something else; not original", mnemonics: [] },
  { word: "Desiccate", definition: "Thoroughly dried up, dehydrated", mnemonics: ["Think about that stuff that they put in your shoe boxes when you by new shoes that says DESICCANT SILICA GEL THROW AWAY! \"DO NOT EAT\" It is there to keep things dry."] },
  { word: "Detached", definition: "impartial, disinterested; unconcerned, distant, aloof", mnemonics: ["dis-attached, it isn't attached"] },
  { word: "Deterrent", definition: "Something that restrains or discourages something immaterial that interferes with or delays action or progress", mnemonics: [] },
  { word: "Diatribe", definition: "Bitter, abusive attack or criticism; rant", mnemonics: ["a tribunal is a court of justice; picture a lawyer going off on a real rant about how guilty someone is: that is a diatribe"] },
  { word: "Didactic", definition: "Intended to instruct; teaching , or teaching a moral lessen", mnemonics: ["When you're really annoyed at your parent for giving you another lecture, just say, \"Why do you have to be so didactic\". That'll shut em up."] },
  { word: "Digress", definition: "Go off-topic when speaking or writing", mnemonics: ["If you want to sound really stuffy and proper, say, \"But forgive me, I digress\" every time that you go mildy off topic."] },
  { word: "Din", definition: "Loud, confused noise, esp. for a long period of time", mnemonics: ["din, din, din, like a ringing bell -jlue"] },
  { word: "Disabuse", definition: "Free someone from a mistake in thinking free someone from a misconception", mnemonics: ["dis is a negative prefix (see many of the next 15 words); here remove an abuse or mistake"] },
  { word: "Discerning", definition: "Having good judgement or insight; able to distinguish mentally", mnemonics: [] },
  { word: "Discredit", definition: "Injure the reputation of, destroy credibility of or confidence in", mnemonics: ["remove the credit"] },
  { word: "Discrepancy", definition: "Difference or inconsistency", mnemonics: ["Dis crap on my pants wasn't there before; must be a discrepancy"] },
  { word: "Discriminating", definition: "Judicious, discerning, having good judgement or insight", mnemonics: [] },
  { word: "Disingenuous", definition: "Insincere, not genuine", mnemonics: ["not genuine"] },
  { word: "Disinterested", definition: "Unbiased, impartial; not interested", mnemonics: ["no interested"] },
  { word: "Disjointed", definition: "Disconnected, not coherent, jerky; having the joints separated", mnemonics: ["not joined: Joints connect things; disjointed things are disconnected."] },
  { word: "Dismiss", definition: "Allow to disperse or leave; fire from a job; put aside or reject, especially after only a brief consideration", mnemonics: [] },
  { word: "Dispassionate", definition: "Unbiased, not having a selfish or personal motivation; calm, lacking emotion", mnemonics: ["not passionate"] },
  { word: "Dispatch", definition: "Speed, promptness; send off or deal with in a speedy way", mnemonics: ["911 dispatcher sends out ambulances promplty in emergencies"] },
  { word: "Disperse", definition: "Scatter, spread widely, cause to vanish", mnemonics: [] },
  { word: "Disposition", definition: "A person's general or natural mood; tendency", mnemonics: [] },
  { word: "Disquieting", definition: "Disturbing, cause anxiety", mnemonics: ["not quieting"] },
  { word: "Disseminate", definition: "Scatter, spread about, broadcast", mnemonics: [] },
  { word: "Dissent", definition: "Disagree or take an opposing view, esp. in relation to a formal body such as a government, political party, or church; such a view to differ in opinion; differ in opinion", mnemonics: ["not assent"] },
  { word: "Dissonance", definition: "Harsh, inharmonious sound; cacophony; disagreement", mnemonics: ["not sonance (not nice sounding or sonorous)"] },
  { word: "Distill", definition: "Purify; extract the essential elements of", mnemonics: [] },
  { word: "Diverge", definition: "Differ, deviate; branch off or turn aside, as from a path", mnemonics: [] },
  { word: "Divest", definition: "Deprive or strip of a rank, title, etc., or of clothing or gear; to sell off holdings (ant: invest)", mnemonics: [] },
  { word: "Divine", definition: "Discover through divination or or supernatural means; perceive by insight", mnemonics: [] },
  { word: "Document", definition: "Support with evidence, cite sources in a detailed way, create documentary evidence of", mnemonics: [] },
  { word: "Dogma", definition: "A system of principles laid down by an authority; established belief", mnemonics: [] },
  { word: "Dormant", definition: "Asleep, inactive, on a break", mnemonics: [] },
  { word: "Dubious", definition: "Doubtfull, questionable, suspect", mnemonics: [] },
  { word: "e.g.", definition: "For example, such as", mnemonics: [] },
  { word: "Eccentric", definition: "Peculiar, odd, deviating from the norm esp. in a whimsical way", mnemonics: [] },
  { word: "Eclectic", definition: "Selecting the best of everything or from many diverse sources", mnemonics: ["SIMILAR TO ELECT"] },
  { word: "Eclipse", definition: "The obscuring of one thing by another, such as the sun by the moon or a person by a more famous or talented person (n); to obscure, darken, make less important,overshadowed (v)", mnemonics: [] },
  { word: "Efficacy", definition: "the quality of being able to produce the intended effect", mnemonics: ["EFFicacy = EFFective - lo"] },
  { word: "Egalitarian", definition: "Related to belief in the equality of all people, esp. in political, economic, or social spheres", mnemonics: ["4 + 4 egals 8."] },
  { word: "Egregious", definition: "Extraordinarily or conspicuously bad; glaring", mnemonics: ["Greg isn't just a little bit bad, he's extra-terribly, unforgivably bad."] },
  { word: "Elated", definition: "Very happy, in high spirits", mnemonics: [] },
  { word: "Elevate", definition: "Raise, lift up; lift the spirits of; move up to a higher rank or status or raise up to a higher spiritual or intellectual plane", mnemonics: [] },
  { word: "Elicit", definition: "Call forth, bring out, evoke", mnemonics: ["explicit elicits various warnings"] },
  { word: "Eloquent", definition: "Marked by forceful, fluid, apt speech; expressive, emotionally moving", mnemonics: [] },
  { word: "Embellish", definition: "Decorate, add ornamentation; enhance (a story) with fictional or fanciful details", mnemonics: [] },
  { word: "Eminent", definition: "Prominent, distinguished, of high rank", mnemonics: [] },
  { word: "Empirical", definition: "Coming from, based on, or able to be verified by experience or experimentation; not purely based on theory", mnemonics: [] },
  { word: "Emulate", definition: "Copy in an attempt to equal or be better than", mnemonics: [] },
  { word: "Enervate", definition: "Weaken, tire", mnemonics: ["Think about it like the opposite of energize. Imagine the Enervater bunny."] },
  { word: "Enhance", definition: "Raise to a higher value, desirability, etc.", mnemonics: [] },
  { word: "Enigma", definition: "Puzzle, mystery, riddle; mysterious or contradictory person", mnemonics: ["Why this video has over 130 million views is an enigma . . . https://www.youtube.com/watch?v=Rk_sAHh9s08"] },
  { word: "Entitlement", definition: "Having the right to certain privileges; believing, sometimes without cause, that one deserves or has a right to certain privileges", mnemonics: [] },
  { word: "Enumerate", definition: "Count or list; specify one-by-one", mnemonics: [] },
  { word: "Ephemeral", definition: "Lasting only a short time, fleeting", mnemonics: [] },
  { word: "Equitable", definition: "Fair, equal, just", mnemonics: [] },
  { word: "Erratic", definition: "Inconsistent, wandering, having no fixed course", mnemonics: [] },
  { word: "Erroneous", definition: "Mistaken, in horror; improper, morally incorrect", mnemonics: ["If Moses supposes his toeses are roses, then Moses supposes erroneously."] },
  { word: "Erudite", definition: "Scholarly, knowledgeable; possessing deep, often systematic, knowledge", mnemonics: [] },
  { word: "Eschew", definition: "Shun, avoid, abstain from", mnemonics: [] },
  { word: "Esoteric", definition: "Understood by or intended for only a few; secret", mnemonics: [] },
  { word: "Estimable", definition: "Worthy of esteem, admirable; able to be estimated", mnemonics: [] },
  { word: "Eulogy", definition: "Speech of praise or written work of praise, esp. a speech given at the funeral", mnemonics: [] },
  { word: "Exacerbate", definition: "Make worse (more violent, severe, etc.), inflame; irritate or embitter (a person)", mnemonics: [] },
  { word: "Exacting", definition: "Very severe in making demands; requiring precise attention", mnemonics: [] },
  { word: "Exculpate", definition: "Clear from guilt or blame", mnemonics: [] },
  { word: "Exhaustive", definition: "Comprehensive, thorough, exhausting a topic or subject, accounting for all possibilities; draining, tending to exhaust", mnemonics: [] },
  { word: "Explicit", definition: "Direct, clear, fully revealed; clearly depicting sex or nudity", mnemonics: [] },
  { word: "Exponent", definition: "Person who expounds or explains; champion, advocate, or representative", mnemonics: [] },
  { word: "Extraneous", definition: "Irrelevant; foreign, coming from without, not belonging", mnemonics: [] },
  { word: "Extrapolate", definition: "Conjecture about an unknown by projecting information about something known; predict by projecting past experience", mnemonics: ["it is the opposite of “extra-polite” to extrapolate about someone you’ve just met."] },
  { word: "Facetious", definition: "Joking, humorous, esp. inappropriately; not serious, concerned with frivolous things", mnemonics: ["focused on the face when you should be thinking about what is underneath"] },
  { word: "Facilitate", definition: "Make easier, help the progress of", mnemonics: [] },
  { word: "Fallacious", definition: "Containing a fallacy, or mistake in logic; logically unsound; deceptive", mnemonics: [] },
  { word: "Fanatical", definition: "Excessively devoted, enthusiastic, or zealous in a uncritical way", mnemonics: ["short version: fan, like sports fan"] },
  { word: "Fanciful", definition: "Whimsical, capricious; imaginary; freely imaginative rather than based on reason or reality", mnemonics: [] },
  { word: "Fathom", definition: "Measure the depth of (usually of water)as with a sounding line; penetrate and discover the meaning of, understand", mnemonics: [] },
  { word: "Feasible", definition: "Possible, logical or likely, suitable", mnemonics: [] },
  { word: "Fidelity", definition: "Faithfulness, loyalty; strict observance of duty; accuracy in reproducing a sound or image", mnemonics: ["Fidelity Investments: faithful company entrusted to handle your money -jlue"] },
  { word: "Figurative", definition: "Metaphorical, based on figures of speech; containing many figures of speech (as fancy sounding writing); relayed to portraying human or animal figures", mnemonics: [] },
  { word: "Finesse", definition: "Extreme delicacy, subtlety, or diplomacy in handling a sensitive situation or in a performance or skill (n); use tact or diplomacy; employ a deceptive strategy (v)", mnemonics: [] },
  { word: "Flag", definition: "Get tired, lose enthusiasm; hang limply or droop", mnemonics: ["a flag droops without wind"] },
  { word: "Fleeting", definition: "Passing quickly, transitory", mnemonics: [] },
  { word: "foment", definition: "incite, instigate, stir up, promote the growth of; apply medicated liquid to a body part", mnemonics: ["When you stir up a bubb", "ferment - to brew up unrest"] },
  { word: "Foreshadow", definition: "Indicate or suggest beforehand, presage", mnemonics: [] },
  { word: "Forfeit", definition: "Surrender or lose as a result of an error, crime, or failure to fulfill an obligation", mnemonics: [] },
  { word: "Fortify", definition: "Strengthen, invigorate, encourage", mnemonics: [] },
  { word: "Fringe", definition: "On the margin, periphery (adj.); the people in a group who hold the most extreme views", mnemonics: [] },
  { word: "Frugal", definition: "Economical, thrifty, not wasteful with money; inexpensive", mnemonics: [] },
  { word: "Futile", definition: "Producing no useful result, ineffective, trivial or unimportant", mnemonics: [] },
  { word: "Gainsay", definition: "Declare false, deny; oppose", mnemonics: ["say against"] },
  { word: "Garrulous", definition: "Talkative, wordy, rambling", mnemonics: ["Garrison from South Park talks a lot"] },
  { word: "Gauche", definition: "Tactless, lacking social grace, awkward, crude", mnemonics: ["`"] },
  { word: "Gawky", definition: "Physically awkward (esp. of a tall, skinny person, often used to describe teenagers)", mnemonics: [] },
  { word: "Germane", definition: "Relevant and appropriate, on-topic", mnemonics: [] },
  { word: "Gist", definition: "Main idea, essence", mnemonics: [] },
  { word: "Glib", definition: "Fluent and easy in a way that suggests superficially or insincerity", mnemonics: [] },
  { word: "Goosebumps", definition: "The \"bumps\" created by hairs standing up on the skin in response to cold, fear, etc.", mnemonics: [] },
  { word: "Gradation", definition: "A progression, a process taking place gradually, in stages; one of these stages", mnemonics: [] },
  { word: "Gregarious", definition: "Social, pertaining to a flock or crowd", mnemonics: [] },
  { word: "Guile", definition: "Clever deceit, cunning, craftiness", mnemonics: [] },
  { word: "Hackneyed", definition: "So commonplace as to be stale; not fresh or original", mnemonics: [] },
  { word: "Hardy", definition: "Bold, brave, capable of withstanding hardship, fatigue, cold, etc.", mnemonics: [] },
  { word: "Haven", definition: "Harbor or port; refuge, safe place", mnemonics: [] },
  { word: "Hearken", definition: "Listen, pay attention to", mnemonics: [] },
  { word: "Hedonist", definition: "Person devoted to pleasure", mnemonics: [] },
  { word: "Heterogenous", definition: "Different in type, incongruous; composed of different types of elements", mnemonics: [] },
  { word: "Hierarchy", definition: "A ranked series; a classification of people according to rank, ability, etc.; a ruling body", mnemonics: [] },
  { word: "Hodgepodge", definition: "Mixture of different kinds of things, jumble", mnemonics: [] },
  { word: "Homogenous", definition: "Of the same kind; uniform throughout", mnemonics: [] },
  { word: "Hyperbole", definition: "Deliberate exaggeration for effect", mnemonics: [] },
  { word: "Idiosyncrasy", definition: "Characteristic or habit peculiar to an individual; peculiar quality, quirk", mnemonics: [] },
  { word: "Illiberality", definition: "Narrow-mindedness, bigotry; strictness or lack of generosity", mnemonics: ["ill + Liberality-> ill + Liberal = anti open minded=>narrowminded or bigoted"] },
  { word: "Imminent", definition: "Ready to occur, impending", mnemonics: [] },
  { word: "Impair", definition: "Make worse, weaken", mnemonics: ["think the opposite of \"repair\""] },
  { word: "Impartial", definition: "Unbiased, fair", mnemonics: [] },
  { word: "Impede", definition: "Hold back, obstruct the progress of", mnemonics: [] },
  { word: "Implication", definition: "Act of implying or that which is implied; close connection, esp. in a incrimination way", mnemonics: [] },
  { word: "Implicit", definition: "implied, not stated directly; involbed in the very essence of something, unquestionable", mnemonics: [] },
  { word: "Implode", definition: "Burst inward", mnemonics: [] },
  { word: "Inadvertent", definition: "Unintentional; characterized by a lack of attention, careless", mnemonics: [] },
  { word: "inasmuch", definition: "In like manner, considering that (contradiction of \"in as much\", generally followed by \"as\")", mnemonics: [] },
  { word: "Incendiary", definition: "Setting on fire, pertaining to arson; arousing strife, rebellion, etc.; \"inflaming\" the senses", mnemonics: [] },
  { word: "Incentive", definition: "Something that encourages greater action or effort, such as a reward", mnemonics: [] },
  { word: "Inchoate", definition: "Just begun, underdeveloped, unorganized", mnemonics: [] },
  { word: "Incipient", definition: "Just beginning; in a very early state", mnemonics: [] },
  { word: "Incongruous", definition: "Out of place, inappropriate, not harmonious", mnemonics: [] },
  { word: "Inconsequential", definition: "Insignificant, unimportant; illogical", mnemonics: [] },
  { word: "Incorporate", definition: "Combine, unite; form a legal corporation; embody, give physical form to", mnemonics: [] },
  { word: "Indeterminate", definition: "Not fixed or determined, indefinite; vague", mnemonics: [] },
  { word: "Indifferent", definition: "Not caring, having no interest; unbiased, impartial", mnemonics: [] },
  { word: "Inform", definition: "Inspire, animate; give substance, essence or context to; be the characteristic quality of", mnemonics: [] },
  { word: "Ingenuous", definition: "Genuine, sincere, not holding back; naive", mnemonics: [] },
  { word: "Ingrained", definition: "Deep-rooted, forming part of the very essence; worked into the fiber", mnemonics: [] },
  { word: "Inherent", definition: "Existing as a permanent, essential quality; intrinsic", mnemonics: [] },
  { word: "Innocuous", definition: "Harmless, inoffensive", mnemonics: [] },
  { word: "Intelligible", definition: "Able to be understood, clear", mnemonics: [] },
  { word: "intractable", definition: "Difficult to control, manage, or manipulate; hard to cure; stuborn", mnemonics: [] },
  { word: "Intrepid", definition: "Fearless, brave, enduring in the face of adversity", mnemonics: [] },
  { word: "Intrinsic", definition: "Belonging to the essential nature of a thing", mnemonics: [] },
  { word: "Jargon", definition: "Vocabulary specific to a group or occupation; convoluted or unintelligible language", mnemonics: [] },
  { word: "Jocular", definition: "Joking or given to joking all the time; jolly, playful", mnemonics: [] },
  { word: "Judicious", definition: "Using good judgement; wise, sensible", mnemonics: ["judge judy can be judicious"] },
  { word: "Juncture", definition: "Critical point in time, such as a crises or a time when a decision in necessary; a place where two things are joined together", mnemonics: [] },
  { word: "Keen", definition: "Sharp, piercing; very perceptive or mentally sharp; intense (of a feeling)", mnemonics: [] },
  { word: "Kudos", definition: "Praise, honor, congratulations", mnemonics: [] },
  { word: "Lackluster", definition: "Not shiny; dull, mediocre; lacking brilliance or vitality", mnemonics: ["lacking luster or shine"] },
  { word: "Laconic", definition: "Using few words, concise", mnemonics: ["Hemingway's prose"] },
  { word: "Lament", definition: "Mourn; express grief, sorrow, or regret (v); an expression of grief esp. as a song or poem (n)", mnemonics: [] },
  { word: "Lampoon, lambast", definition: "A harsh satire (n); ridicule or satirize (v)", mnemonics: [] },
  { word: "Landmark", definition: "Object (such as a building) that stands out and can be used to navigate by; a very important place, event, etc.", mnemonics: ["Mark the land so it is noticeable"] },
  { word: "Languid", definition: "Drooping from exhaustion. sluggish, slow; lacking in sprit", mnemonics: [] },
  { word: "Lassitude", definition: "Tiredness, weariness; lazy indifference", mnemonics: ["Lassie is tired."] },
  { word: "Laudable", definition: "Worthy of praise", mnemonics: ["praise the \"laud\" (lord)"] },
  { word: "Lavish", definition: "Abundant or giving in abundance; marked by excess (adj.); give very generously (v)", mnemonics: [] },
  { word: "Layperson", definition: "A person who is not a member of the clergy or not a member of a particular profession (such as medicine, law, etc.)", mnemonics: ["laymen's or common man's terms"] },
  { word: "Levity", definition: "Lightness (of mind, spirit, or mood) or lack of seriousness, sometimes in an inappropriate way", mnemonics: ["to levitate, be light"] },
  { word: "Levy", definition: "Collect tax from, wage war on, or enlist for military service (v); act of collecting tax or amount owed, or the drafting of troops into military service (n)", mnemonics: [] },
  { word: "Liberal", definition: "Favorable to progress or reform; believing in maximum possible individual freedom; tolerant, open-minded; generous(adj.); a person with such beliefs or practices (n)", mnemonics: [] },
  { word: "Libertine", definition: "Morally or sexually unrestrained person, freethinker (regarding religion)", mnemonics: [] },
  { word: "Likewise", definition: "Also, in addition to; similarly, in the same way", mnemonics: [] },
  { word: "Log", definition: "Keep a record of, write down; travel for or at a certain distance or speed (v); a written record (n)", mnemonics: [] },
  { word: "Loquacious", definition: "Talkative, wordy", mnemonics: [] },
  { word: "Lucid", definition: "Clear, easy to understand; rational, sane", mnemonics: [] },
  { word: "Lull", definition: "Soothe or cause to fall asleep (as in lullaby); quite down; make to feel secure, sometimes falsely (v); a period of calm or quiet (n)", mnemonics: [] },
  { word: "Makeshift", definition: "A temporary, often improvised, substitute (n); improvised for temporary use (adj.)", mnemonics: [] },
  { word: "Malleable", definition: "Able to be bent, shaped, or adapted", mnemonics: ["shape it with a mallet"] },
  { word: "Maverick", definition: "Rebel, individualist, dissenter", mnemonics: [] },
  { word: "Mendacious", definition: "Lying, habitually dishonest", mnemonics: ["Some MEN are auDACIOUS enough to lie to your face, even when they know you know that they're being mendacious"] },
  { word: "Mercurial", definition: "Quickly and unpredictable changing moods; fickle, flighty", mnemonics: [] },
  { word: "Metamorphosis", definition: "A complete change or transformation (in biology, a change such as a caterpillar becoming a pupa and then a butterfly)", mnemonics: [] },
  { word: "Meticulous", definition: "Taking extreme care in regards to details; precise, fussy", mnemonics: [] },
  { word: "Mitigate", definition: "Make less sever; lessen or moderate (damage, gried, pain, etc.)", mnemonics: [] },
  { word: "Modest", definition: "humble; simple rather than showy; decent (esp. \"covering up\" in terms of dress); small, limited", mnemonics: [] },
  { word: "Molify", definition: "Calm or soothe (an angry person); lessen or soften", mnemonics: [] },
  { word: "Monotony", definition: "Sameness or repetitiousness to the point of being boring; lack variation, uniformity, esp. repetition in sound", mnemonics: [] },
  { word: "Moreover", definition: "Besides; in addition to what was just stated", mnemonics: [] },
  { word: "Mores", definition: "Customs, manners, or morals of a particular group", mnemonics: [] },
  { word: "Mundane", definition: "Common, ordinary, everyday", mnemonics: [] },
  { word: "Naive", definition: "Simple and unsophisticated, unsuspecting, lacking worldly experience and critical judgement", mnemonics: [] },
  { word: "Nascent", definition: "Coming into existence, still developing", mnemonics: [] },
  { word: "Negate", definition: "Deny or refute; make void or cause to be ineffective", mnemonics: [] },
  { word: "Net", definition: "Remaining after expenses or other factors have been deducted; ultimate (adj.); too bring in as profit, or to catch as in a net (v)", mnemonics: [] },
  { word: "Nevertheless or Nonetheless", definition: "However, even so, despite that", mnemonics: [] },
  { word: "Notoriety", definition: "Ill fame; the state of being well known for a disgraceful reason", mnemonics: ["notability of a bad variety"] },
  { word: "Novel", definition: "New, fresh, original", mnemonics: [] },
  { word: "Nuance", definition: "A subtle difference in tone, meaning, expression, etc.", mnemonics: [] },
  { word: "Objective", definition: "Factual, related to reality or physical objects; not influenced by emotions, unbiased", mnemonics: [] },
  { word: "Obsequious", definition: "Servile, very compliant, fawning", mnemonics: [] },
  { word: "Obsolete", definition: "", mnemonics: ["Obviously, it arrived SO LATE that it is obsolete"] },
  { word: "Obstinate", definition: "Stubborn or hard to control", mnemonics: ["My friend Nate is so stubborn"] },
  { word: "Obviate", definition: "Prevent, eliminate, or make unnecessary", mnemonics: ["Elimin-ate what's ob-vious."] },
  { word: "Occult", definition: "The supernatural (n); pertaining to magic, astrology, etc.; mysterious, secret or hidden (adj.); to hide, to shut off from view (v)", mnemonics: ["black magic is a cult"] },
  { word: "Offhand", definition: "Casual, informal; done without preparation or forethought; rude in a short way, brusque", mnemonics: [] },
  { word: "Officious", definition: "Excessively eager in giving unwanted advice or intruding where one is not wanted; meddlesome, pushy", mnemonics: ["You give awful advice!"] },
  { word: "Offset", definition: "Counteract, compensate for (v); a counterbalance(n)", mnemonics: [] },
  { word: "Onerous", definition: "Burdensome, oppressive, hard to endure", mnemonics: [] },
  { word: "Opaque", definition: "Not translucent; not allowing light, heat, etc. to pass through; dark, dull, unclear or stupid", mnemonics: [] },
  { word: "Optimal or Optimum", definition: "Best, most desirable or favorable", mnemonics: [] },
  { word: "Orthodox", definition: "adhering to a traditional, established faith, or to anything customary or commonly accepted", mnemonics: [] },
  { word: "Oscillate", definition: "Swing back and forth; waver, change one's mind", mnemonics: [] },
  { word: "Outstrip", definition: "Surpass, exceed; be larger or better than; leave behind", mnemonics: [] },
  { word: "Overshadow", definition: "Cast a shadow over, darken; dominate, make to seem less important", mnemonics: [] },
  { word: "Paradigm", definition: "Model or pattern; worldview, set of shared assumptions, values, etc.", mnemonics: [] },
  { word: "Paradox", definition: "Contradiction that is actually true", mnemonics: [] },
  { word: "Pariah", definition: "Social outcast, untouchable", mnemonics: [] },
  { word: "Partial", definition: "Biased, prejudiced, favoring one over others; having a special liking for something or someone (usually partial to)", mnemonics: [] },
  { word: "Partisan", definition: "Devoted to a particular group, case, etc.(adj); fervent supported of a group, party, idea, etc. guerrilla fighter(b)", mnemonics: [] },
  { word: "Patent", definition: "Obvious, apparent, plain to see (adj.); a letter from a govt. guaranteeing an inventor the rights to his or her invention (n)", mnemonics: [] },
  { word: "Pathological", definition: "Relating to or caused be disease; relating to compulsive bad behavior", mnemonics: [] },
  { word: "Patronizing", definition: "Condescending, having a superior manner, treating as an inferior", mnemonics: [] },
  { word: "Paucity", definition: "Scarcity, the state of being small in number", mnemonics: [] },
  { word: "Peccadillo", definition: "Small sin or fault", mnemonics: [] },
  { word: "Pedestrian", definition: "Ordinary, dull, commonplace", mnemonics: [] },
  { word: "Penchant", definition: "Liking or inclination (usually penchant for)", mnemonics: ["Be enchanted by = to like it or be inclined towards it"] },
  { word: "Perfidious", definition: "Disloyal, treacherous, violating one's trust", mnemonics: ["Opposit of perfect+fidelious = perfect unfidelious => Unfaithful"] },
  { word: "Peripheral", definition: "Relating to or making up an outer boundary or region; not of primary importance, fringe", mnemonics: [] },
  { word: "Permeate", definition: "Spread or penetrate throughout", mnemonics: [] },
  { word: "Pervasive", definition: "Tending to spread throughout", mnemonics: [] },
  { word: "Philanthropy", definition: "Efforts to improve the well-being of humankind, generally through giving money", mnemonics: [] },
  { word: "Phony", definition: "fake, counterfeit; insincere, not genuine", mnemonics: [] },
  { word: "Pious", definition: "Devout; religiously reverent and dutiful", mnemonics: [] },
  { word: "Pith", definition: "Core, essence; significance or weight", mnemonics: [] },
  { word: "Placate", definition: "Satisfy or calm down (an angry or dissatisfied person), esp. by conciliatory gestures", mnemonics: [] },
  { word: "Placid", definition: "Peaceful, calm, tranquil", mnemonics: [] },
  { word: "Plastic", definition: "Able to be shaped or formed; easily influenced", mnemonics: [] },
  { word: "Plausible", definition: "Believable; having the appearance of truth", mnemonics: [] },
  { word: "Plummet", definition: "Plunge, fall straight down", mnemonics: [] },
  { word: "Polarized", definition: "Divided into sharply opposed groups", mnemonics: [] },
  { word: "Ponderous", definition: "Heavy, bulky and unwieldy; dull. labored", mnemonics: [] },
  { word: "Posthumous", definition: "Happening or continuing after death", mnemonics: [] },
  { word: "Potentate", definition: "Ruler, person of great power", mnemonics: ["Potent = powerful"] },
  { word: "Pragmatic", definition: "Practical; dealing with actual facts", mnemonics: [] },
  { word: "Preamble", definition: "Introductory statement, preface", mnemonics: [] },
  { word: "Precarious", definition: "Unstable, insecure, dangerous", mnemonics: [] },
  { word: "Precursor", definition: "Something that comes before, esp. something that also announces or suggests something on its way", mnemonics: [] },
  { word: "Predisposed", definition: "Having an inclination or tendency beforehand; subscribe", mnemonics: [] },
  { word: "Preempt", definition: "Prevent; take the place of, supplant; take before someone else can", mnemonics: [] },
  { word: "presumptive", definition: "Based on inference or assumption; providing reasonable grounds for belied", mnemonics: [] },
  { word: "Presumptuous", definition: "Too bold of forward; going beyond that which is proper", mnemonics: [] },
  { word: "Pretentious", definition: "Claiming or demanding a position of importance or dignity, esp. when unjustified; showing off, creating a deceptive, false show of worth", mnemonics: [] },
  { word: "Principled", definition: "Having high moral standards", mnemonics: [] },
  { word: "Pristine", definition: "In an original, pure state; uncorrupted", mnemonics: [] },
  { word: "Probity", definition: "Honesty, integrity", mnemonics: [] },
  { word: "Prodigal", definition: "Wasteful, extravagant; giving abundantly, lavish", mnemonics: ["The Prodigal son"] },
  { word: "Prodigious", definition: "Extraordinarily large, impressive, etc.", mnemonics: [] },
  { word: "Profligate", definition: "Completely and shamelessly immoral, or extremely wasteful", mnemonics: [] },
  { word: "Profound", definition: "Very insightful, penetrating deeply into a subject; pervasive, intense, \"down to the very bottom\"; at the very bottom", mnemonics: [] },
  { word: "Profuse", definition: "Abundant, extravagant, giving or given freely", mnemonics: [] },
  { word: "Prohibitive", definition: "Tending to forbid something, or serving to prevent", mnemonics: [] },
  { word: "Proliferate", definition: "Increase or spread rapidly or excessively", mnemonics: [] },
  { word: "Prologue", definition: "Introductory part to a book, play, etc.", mnemonics: [] },
  { word: "Pronounced", definition: "Distinct, strong, clearly indicated", mnemonics: [] },
  { word: "Propriety", definition: "Conforming to good manners or appropriate behavior", mnemonics: [] },
  { word: "Prosaic", definition: "Dull, ordinary", mnemonics: ["Prosaic sounds so interesting. But it means the opposite - dull, uninteresting, mundance"] },
  { word: "Proscribe", definition: "Prohibit, outlaw; denounce; exile or banish", mnemonics: [] },
  { word: "Prospective", definition: "Potential, in the future", mnemonics: [] },
  { word: "Prudent", definition: "Wise in practical matters, carefully providing for the future", mnemonics: [] },
  { word: "Pugnacious", definition: "Inclined to fight, combative", mnemonics: ["Pugs are ready to fight!"] },
  { word: "Qualified", definition: "Modified, limited, conditional on something else", mnemonics: [] },
  { word: "Quandary", definition: "Uncertainty or confusion about what to do, dilemma", mnemonics: ["Quandary or Laundry? I am so confused!"] },
  { word: "Quibble", definition: "Make trivial arguments or criticism, find faults in a petty way, esp. to evade something more important", mnemonics: [] },
  { word: "Quotidian", definition: "Daily; everyday, ordinary", mnemonics: [] },
  { word: "Ranks", definition: "Personnel; a group of people considered all together", mnemonics: [] },
  { word: "Reap", definition: "Harvest, such as by cutting; gather; get as a result of one's effort", mnemonics: [] },
  { word: "Recluse", definition: "Person who lives in seclusion", mnemonics: [] },
  { word: "Refute", definition: "Prove to be false", mnemonics: [] },
  { word: "Relegate", definition: "Send or commit to an inferior place, rank, condition, etc.; exile, banish; assign (task) to someone else", mnemonics: [] },
  { word: "Remedial", definition: "Providing a remedy, curative; correcting a deficient skill", mnemonics: [] },
  { word: "Render", definition: "Give, submit, surrender; translate declare", mnemonics: [] },
  { word: "Replete", definition: "Supplied in abundance, filled gorged (used with with)", mnemonics: [] },
  { word: "Reproach", definition: "Blame, disgrace (n); criticize, express disappointment in(v)", mnemonics: [] },
  { word: "Repudiate", definition: "Reject, cast off, deny tat something has authority", mnemonics: [] },
  { word: "Requite", definition: "Reciprocate, repay, or revenge", mnemonics: [] },
  { word: "Rescind", definition: "Annul, repeal, make void", mnemonics: [] },
  { word: "Resolution", definition: "The quality of being firmly determined; resolving to do something; a formal judgement, esp. decided by a vote", mnemonics: [] },
  { word: "Resolve", definition: "Find a solution to; firmly decide to do something; decide by formal vote(v); firmness of purpose (n)", mnemonics: [] },
  { word: "Respectively", definition: "In the order given", mnemonics: [] },
  { word: "Restive", definition: "Impatient or uneasy under the control of another; resisting being controlled", mnemonics: [] },
  { word: "Reticent", definition: "Not talking much; private (of a person), restrained, reserved", mnemonics: ["\"I'll give you a cent for your thoughts,\" \"No! I don't want to share my feelings\""] },
  { word: "Retrospective", definition: "Looking to the past or backward; applying to the past, retroactive (adj.); An art exhibit of an artist's work over a long period of time (n)", mnemonics: [] },
  { word: "Reverent", definition: "Feeling or expressing very deep respect and awe", mnemonics: [] },
  { word: "Rhetoric", definition: "The art or study of persuasion through speaking or writing; language that is elaborate or pretentious but actually empty, meaning little", mnemonics: [] },
  { word: "Rife", definition: "Happening frequently, abundant, currently being reported", mnemonics: [] },
  { word: "Rudimentary", definition: "Elementary, relating to the basics; underdeveloped, primitive", mnemonics: [] },
  { word: "Rustic", definition: "Relating to country life, unsophisticated; primitive; made of rough wood (adj.); a rural or uncultured person (n)", mnemonics: [] },
  { word: "Sacrosanct", definition: "Sacred, inviolable, not to be trespassed on or violated; above any criticism", mnemonics: ["sacred saint=> most holy"] },
  { word: "Sagacious", definition: "Wise; showing good judgement and foresight", mnemonics: [] },
  { word: "Salubrious", definition: "Healthful, promoting health", mnemonics: ["Salud! (to your health!)"] },
  { word: "Sanction", definition: "Permission or approval, something that gives support or authority to something else (n); to allow, confirm, ratify (v); OR a legal action by one or more countries against anther country to get it to comply (n); to place sanctions or penalties on (v)", mnemonics: [] },
  { word: "Sanguine", definition: "Cheerfully optimistic, hopeful; reddish, ruddy (as in rosy-red cheeks indicating health or vitality)", mnemonics: [] },
  { word: "Sap", definition: "The inner fluid of a plant or any essential body fluid; energy; vitality; a person taken advantage of (n); undermine, weaken, tire out (v)", mnemonics: [] },
  { word: "Satiate or Sate", definition: "To fully satisfy; to go beyond satisfying to the point of excess (possibly inducing disgust, tiredness, etc.)", mnemonics: [] },
  { word: "Saturate", definition: "Soak or imbue thoroughly; cause a substance to unite with the greatest possible amount of another substance", mnemonics: [] },
  { word: "Savor", definition: "Appreciate fully, taste or smell with pleasure", mnemonics: [] },
  { word: "Scant", definition: "Not enough or barely enough", mnemonics: [] },
  { word: "Scathing", definition: "Severe, injurious; bitterly harsh or critical (as a remark)", mnemonics: [] },
  { word: "Secular", definition: "Not religious or holy; pertaining to worldly things", mnemonics: [] },
  { word: "Sedulous", definition: "Persevering, persistent, diligent in one's efforts", mnemonics: [] },
  { word: "Sentient", definition: "Conscious; experiencing sensation or perceiving with the senses", mnemonics: [] },
  { word: "Simultaneous", definition: "At the same time", mnemonics: [] },
  { word: "Skeptic", definition: "Person inclined to doubting or questioning generally accepted beliefs", mnemonics: [] },
  { word: "Skirt", definition: "Border, lie along the edge of, go around; evade", mnemonics: [] },
  { word: "Slack", definition: "Loose, negligent, lazy, weak (adj.); neglect to do one's duties; loosen up, relax (v); period of little work (n)", mnemonics: [] },
  { word: "Slew", definition: "A large number or quantity", mnemonics: [] },
  { word: "Slight", definition: "Small, not very important, slender or delicate (adj.); treat as though not very important; snub, ignore(v); an act of treating in this way; a discourtesy (n)", mnemonics: [] },
  { word: "Solicitous", definition: "Concerned or anxious (about another person), expressing care; eager or desirous; very careful", mnemonics: [] },
  { word: "Soporific", definition: "Causing sleep; sleepy, drowsy (adj.); something that causes sleep (n)", mnemonics: [] },
  { word: "Sound", definition: "Measure the depth of (usually of water) as with a sounding line; penetrate and discover the meaning of, understand (usually as sound the depths )", mnemonics: [] },
  { word: "Spartan", definition: "Very disciplined and stern; frugal, living simply; austere; suggestive of the ancient Spartans", mnemonics: [] },
  { word: "Spate", definition: "Sudden outpouring or rush; flood", mnemonics: [] },
  { word: "Spearhead", definition: "Be the leader of", mnemonics: [] },
  { word: "Specious", definition: "Seemingly true but actually false; deceptively attractive", mnemonics: [] },
  { word: "Spectrum", definition: "A broad range of nevertheless related qualities or ideas, esp. those that overlap to create a continuous series (as in a color spectrum, where each color blends into the next in a continuous way)", mnemonics: [] },
  { word: "Speculate", definition: "Contemplate; make a guess or educated guess about; engage in a risky business transaction, gamble", mnemonics: [] },
  { word: "Sporadic", definition: "Occasional, happening irregularly or in scattered locations", mnemonics: [] },
  { word: "Sportive", definition: "Playful, merry, joking around, done \"in sport\" (rather than intended seriously)", mnemonics: ["Daniel is on Tinder for sportive reasons"] },
  { word: "Standing", definition: "Status, rank, reputation (n); existing indefinitely, not movable (adj.)", mnemonics: [] },
  { word: "Stark", definition: "Complete, total, utter; harsh or grim; extremely simple, severe, blunt, or pain", mnemonics: [] },
  { word: "Static", definition: "Fixed, not moving or changing, lacking vitality", mnemonics: [] },
  { word: "Status quo", definition: "Existing state or condition", mnemonics: [] },
  { word: "Stingy", definition: "Not generous with money, reluctant to spend or give", mnemonics: [] },
  { word: "Stoic or stoical", definition: "Indifferent to pleasure or pain, enduring without complaint; person indifferent to pleasure or pain (n)", mnemonics: [] },
  { word: "Stolid", definition: "unemotional, showing little emotion, not easily moved", mnemonics: ["Think about it like stoic + solid. IE not moving"] },
  { word: "Stymie or stymy", definition: "Block, hinder, or thwart (v); an obstacle (n)", mnemonics: [] },
  { word: "Subjective", definition: "Existing in the mind or relating to one's own thoughts, opinions, emotions, etc.; personal, individual, based on feelings", mnemonics: [] },
  { word: "Subside", definition: "Sink, settle down, become less active, return to a normal level", mnemonics: [] },
  { word: "Substantiate", definition: "Support with evidence or proof; give a materiel existence to", mnemonics: [] },
  { word: "Succeeding", definition: "Coming after or following", mnemonics: [] },
  { word: "Supersede", definition: "Replace, take the position of, cause to be disregarded as void or obsolete", mnemonics: [] },
  { word: "Supplicate", definition: "Pray humbly; ask, beg, or seek in a humble way", mnemonics: [] },
  { word: "Surfeit", definition: "Excess, excessive amount, overindulgence", mnemonics: [] },
  { word: "Surmise", definition: "Guess, infer, think or make an opinion with incomplete information", mnemonics: [] },
  { word: "Sycophant", definition: "Servile flatterer, parasitic person who fawns in order to get ahead", mnemonics: ["Imagine a psycho-ant that keeps telling you how great you are", "Sick parasite"] },
  { word: "Synchronous", definition: "Happening at the same time; occurring at the same rate and thus happening together repeatedly", mnemonics: [] },
  { word: "Table", definition: "Lay aside to discuss later, ofter as a way to postpone discussion indefinitely", mnemonics: [] },
  { word: "Tacit", definition: "Understood without being said; implied, not stated directly; silent", mnemonics: [] },
  { word: "Taciturn", definition: "Reserved or uncommunicative in speech; saying little.", mnemonics: [] },
  { word: "Tangential", definition: "Only slightly relevant, going off topic", mnemonics: [] },
  { word: "Temparence", definition: "Moderation, self-control, esp. regarding alcohol or other desires or pleasures; total abstinence from alcohol", mnemonics: [] },
  { word: "Tenuous", definition: "Long and thin, slender; flimsy, having little substance", mnemonics: [] },
  { word: "Timely", definition: "Well-timed, happening at a suitable time", mnemonics: [] },
  { word: "Timorous", definition: "Fearful, timid", mnemonics: ["timid Tim"] },
  { word: "Tirade", definition: "Bitter, abusive criticism or verbal attack", mnemonics: [] },
  { word: "Torpor", definition: "Sluggishness, lethargy, apathy; a period of inactivity", mnemonics: ["torpor = torpedo (slow moving)"] },
  { word: "Torrid", definition: "Very hot, parching, burning; passionate", mnemonics: ["torrid = torch (burning flame)"] },
  { word: "Tractable", definition: "Easily controlled or managed, docile; easily shaped or molded", mnemonics: [] },
  { word: "Transitory", definition: "Temporary, short-lived, not lasting", mnemonics: [] },
  { word: "Trifling", definition: "Trivial, not very important; so small as to be unimportant; frivolous, shallow", mnemonics: [] },
  { word: "Trite", definition: "Lacking freshness and originality, lacking effectiveness due to overuse, cliche", mnemonics: ["Miss-spelled store names, like Rite-Aid, are Trite: they lack freshness and are overused"] },
  { word: "Ubiquitous", definition: "Existing everywhere at the same time", mnemonics: [] },
  { word: "Undermine", definition: "Weaken, cause to collapse by digging away at the foundation (of a building or an argument ); injure or attack in a secretive or underhanded way", mnemonics: [] },
  { word: "Underscore", definition: "Emphasize (or, literally, to underline text)", mnemonics: [] },
  { word: "Unearth", definition: "Dig up, uncover, expose", mnemonics: ["Take off the earth that was on top of something"] },
  { word: "Unequivocal", definition: "Unambiguous, clear, absolute; having only one possible meaning", mnemonics: [] },
  { word: "Unprecedented", definition: "Never before known or seen, without having happened previously", mnemonics: [] },
  { word: "Unseemly", definition: "Improper, inappropriate, against the rules of taste or politeness", mnemonics: [] },
  { word: "Vacillate", definition: "Waver in one's mind or opinions, be indecisive", mnemonics: [] },
  { word: "Venerate", definition: "Revere, regard with deep respect and awe", mnemonics: ["You should only venerate things that are truly great"] },
  { word: "Veracity", definition: "Truthfulness, accuracy; habitual adherence to the truth", mnemonics: ["Ver comes from latin for truth; this basically means \"truthyness\""] },
  { word: "Verbose", definition: "Wordy", mnemonics: ["Using a lot of verbs"] },
  { word: "Viable", definition: "Capable of living (or growing, developing, etc.); practical, workable", mnemonics: ["If it is viable, it is able to live."] },
  { word: "Vintage", definition: "Related to items of high quality from a previous era, old fashioned antique (adj.); the wine of a particular year (n)", mnemonics: ["Originally related to wine of a given year; later adopted to describe anything in which age is being used as an asset increasing its value rather than just making it into old, useless, out-of-date crap"] },
  { word: "Virtual", definition: "Existing only in the mind or by means of a computer network; existence in results or in essence but not officially or in name", mnemonics: [] },
  { word: "Vituperate", definition: "Verbally abuse, rebuke or criticize harshly", mnemonics: ["If you don't cooperate, I will vituperate."] },
  { word: "Volatile", definition: "Varying, inconsistent, fleeting; tending to violence, explosive;", mnemonics: ["From latin for \"to fly\"; something that could fly off at any moment"] },
  { word: "Warranted", definition: "Justified, authorized (warrant can mean to justify or a justification, but can also mean to vouch for or guarantee)", mnemonics: ["Despite such hits as 'I saw Red' and 'Cherry Pie', I don't really think that the success of 1980s hair-metal hard-rock band Warrant was really justified"] },
  { word: "Wary", definition: "Watchful, motivated by caution, on guard against danger", mnemonics: ["Waiting for something scARY."] },
  { word: "Whereas", definition: "While on the contrary, considering that", mnemonics: [] },
  { word: "Whimsical", definition: "Marked or motivated by whims (odd, fanciful ideas); erratic, unpredictable", mnemonics: ["Imagine a musical in which all characters were riding bicycles on a giant icycle while eating popsicals: thats pretty whimsical"] },
  { word: "Wily", definition: "Crafty, cunning, characterized by tricks or artifice", mnemonics: ["Wile E. Cayote"] },
  { word: "Zeal", definition: "Great fervor or enthusiasm for a cause, person, etc., tireless diligence in furthering that cause; passion, ardor", mnemonics: ["Think of a crowd of people going crazy at the Zoo, watching a seal."] },
  { word: "Zenith", definition: "High point, culmination", mnemonics: ["It really seems like the high point of Zenith TVs was back in the 1990s, during the reign of the \"fat-back\" TV, before their acquisition by Samsung."] }
];
